### ISSUE TITLE
Project Could use a Wiki and/or Website

### ISSUE THREAD

**Issue by afiaka87** [lucidrains/DALLE-pytorch#101]
I've kind of been misusing the Issues lately to post findings/discoveries from my training. However, I think a more appropriate place for such things would be on either a github wiki, a github pages website or both.

I'd be happy to write up the first few articles. Frequently Asked Questions, How Can I Help,Troubleshooting, that sort of thing.

 I also think it would be a good place to document what is actually needed to train a "full dalle" in terms of dataset, costs, compute and development effort. With pricey GPU's in the mix, this stuff is less agile and more waterfall because it just costs too much money to "move fast and break things".

Anyway, the Issues area is kinda filled with useful tidbits from various postings like that. It's getting a bit messy in there too ha.

**Comment by robvanvolt** [comment]
I agree with you @afiaka87 ! This might speed up things, also we could write a script in a similar fashion as the developer of the dall-e-pytorch repo did (https://github.com/yashbonde/dall-e-baby).

He wrote a script, which downloads the pictures and captions automatically and sanitizes them!

If we write some code in a similar fashion for the upcoming wikipedia image-text data, the yfcc100m and the open-images, we might actually get to a dataset close to that of the original Dall-E project!!

**Comment by afiaka87** [comment]
Oh wow, definitely downloading every single thing I can from that repo. Extremely helpful, thanks.

**Comment by CDitzel** [comment]
so there is the discussion section of this repo, a feature recently introduced by github...

**Comment by afiaka87** [comment]
> so there is the discussion section of this repo, a feature recently introduced by github...

oh wow. thanks, i forgot this existed.
