### ISSUE TITLE
CLIP reranks images not visual tokens

### ISSUE THREAD

**Issue by deepylt** [lucidrains/DALLE-pytorch#11]
I think according to the blog of DALL_E, CLIP is used to rerank the decoded images instead of the visual tokens. Therefore, a CLIP model pre-trained on raw images should be used.

**Comment by lucidrains** [comment]
@deepylt oh you are right! switched it over to state of the art vision transformer in https://github.com/lucidrains/DALLE-pytorch/commit/e0456ae00ca970f17b6f2abd529f888cc4154eba as in https://github.com/lucidrains/vit-pytorch

**Comment by lucidrains** [comment]
@deepylt it's going to be really hard for the average person to train a visual transformer though, i wonder if i should bring distillation into this repository https://github.com/lucidrains/vit-pytorch#distillation 🤔

**Comment by deepylt** [comment]
I don't think we need to train a ViT model. A pretrained ViT model, for example provided by [vit-pytorch]([https://github.com/lucidrains/vit-pytorch](vi))  could be directly used to rerank the images.  We just need to import the model and load the pretrained parameters.

**Comment by lucidrains** [comment]
@deepylt yea that sounds good, I haven't ported over the weights yet, but maybe I'll do it for this project!
