### ISSUE TITLE
Resuming uses more VRAM than starting from scratch with same parameters

### ISSUE THREAD

**Issue by awilson9** [lucidrains/DALLE-pytorch#114]
I'm able to run with the following parameters
```
MODEL_DIM = 512
TEXT_SEQ_LEN = 256
DEPTH = 64
HEADS = 62
DIM_HEAD = 64
BATCH_SIZE=16
```
using the VQGanVAE1024 vae, however when I try to resume with these parameters, I am hit with cuda out of memory errors. I can't get past one step until I lower the batch size to 10. Any ideas why resuming with the same parameters would be more memory intensive?

**Comment by lucidrains** [comment]
@awilson9 when you are resuming, are you still passing the `--taming` flag?

**Comment by afiaka87** [comment]
@awilson9 this is also a known bug in jupyter notebooks, if you're using a jupyter/colab notebook. Even if you delete all your objects and call tuda.torch.empty_cache(), you may still need to do a full kernel restart in order to get back all your VRAM.

**Comment by awilson9** [comment]
I am not but I slightly modified `train_dalle` to just use the VQGanVAE by default on resume

```
if RESUME:
    dalle_path = Path(DALLE_PATH)
    assert dalle_path.exists(), 'DALL-E model file does not exist'

    loaded_obj = torch.load(str(dalle_path))

    dalle_params, vae_params, weights = loaded_obj['hparams'], loaded_obj['vae_params'], loaded_obj['weights']

    vae = VQGanVAE1024()

    dalle_params['vae'] = vae

    IMAGE_SIZE = vae.image_size
    
    
   ...
   dalle = DALLE(**dalle_params).cuda()
   ```
   
And not running in a notebook, just running directly on my machine. It seems to be a legitimate OOM error trying to reserve more than is available, this was also after rebooting my machine

```
RuntimeError: CUDA out of memory. Tried to allocate 1.54 GiB (GPU 0; 23.69 GiB total capacity; 18.51 GiB already allocated; 1.45 GiB free; 20.26 GiB reserved in total by PyTorch)
```

**Comment by awilson9** [comment]
After a little more debugging, it seems there is around 3.5GB more memory allocated at the start of training when resuming vs starting from scratch

Memory usage when resuming prior to first call to loss.backward()
```
current memory allocated: 6767.560546875
max memory allocated: 6767.560546875
cached memory: 6836.0
```

Memory usage on fresh start prior to first call to loss.backward()
```
current memory allocated: 3383.7177734375
max memory allocated: 3383.7177734375
cached memory: 3428.0
```

That's about exactly the size of my `dalle.pt` file, is it perhaps being loaded into memory twice?

**Comment by awilson9** [comment]
I believe cuda is keeping the reference to `loaded_obj` in memory.

After calling `loaded_obj = torch.load(str(dalle_path))`, memory is as follows:
```
current memory allocated: 3384.2177734375
max memory allocated: 3384.2177734375
cached memory: 3428.0
```
After calling `dalle = DALLE(**dalle_params).cuda()` memory jumps to what is displayed above:
```

**Comment by awilson9** [comment]
The fix looks to be mapping the call to torch.load to the cpu rather than the gpu

```
loaded_obj = torch.load(str(dalle_path), map_location='cpu')
```

Adding this map location argument got rid of the memory errors for me

**Comment by afiaka87** [comment]
@awilson9 
great work. could you make a pull request with this fix?

**Comment by afiaka87** [comment]
@lucidrains I've indepently verified that this is a bug and that @awilson9 has fixed it. I'll make a PR now.

**Comment by afiaka87** [comment]
@lucidrains here ya go :) https://github.com/lucidrains/DALLE-pytorch/pull/118

thanks @awilson9

**Comment by lucidrains** [comment]
thanks @afiaka87  :)

**Comment by awilson9** [comment]
thanks for submitting the PR, wasn't able to get around to this yesterday
