### ISSUE TITLE
Github "Discussions" Not Great, Might Need Discord Now (Edit: Eh, It's all Bad)

### ISSUE THREAD

**Issue by afiaka87** [lucidrains/DALLE-pytorch#116]
I think we're probably at a point where we need some sort of real-time async chat like Discord/Riot. I just can't find anything in discussions. I dont know i'm probably not using it properly. I'd love to try to find you all on EleutherAI's discord chat but I'm honestly not clear on the nature of lucidrains affiliation with EleutherAI and they're having enough trouble dealing with PR as is. I dont think it's a good idea for any of us to pile on with accidentally hyperbolic statements about any of the results we're getting until we've done some _very_ rigorous analysis in comparison to OpenAI's results. 

Could we either get a dedicated DALLE-pytorch channel in eleutherAI's channel or I guess just a new dedicated Discord server? 

I'd personally prefer we use something like matrix/riot but I realize Discord works well and is probably more accessible.

**Comment by robvanvolt** [comment]
I agree, I had the same thoughts yesterday...
Something 'agnostic' or 'independent wouldn't be bad, would it?

> I dont think it's a good idea for any of us to pile on with accidentally hyperbolic statements about any of the results we're getting until we've done some very rigorous analysis in comparison to OpenAI's results.

Also, I agree with your statement here.

**Comment by CDitzel** [comment]
I would be in as well. Discord works for me. Who is in charge of creating a new channel there dedicated solely to Dalle?

**Comment by robvanvolt** [comment]
I've created both, a discord and a matrix server (I also don't mind if anybody else is hosting the server, I just wanted to get things going! :-)):

1) DALLE-pytorch(+dalle-pytorch:matrix.org) is the adress for Element (Matrix)
2) https://discord.gg/R64srpKJ for Discord

Maybe we can have a look at both and decide tomorrow which one we keep?

**Comment by afiaka87** [comment]
> I've created both, a discord and a matrix server (I also don't mind if anybody else is hosting the server, I just wanted to get things going! :-)):
> 
> 1. DALLE-pytorch(+dalle-pytorch:matrix.org) is the adress for Element (Matrix)
> 2. https://discord.gg/R64srpKJ for Discord
> 
> Maybe we can have a look at both and decide tomorrow which one we keep?

Fantastic!
If you don't know how to join the element room, go to app.element.io, sign in with Github and search for the community "dalle-pytorch". I vote element. It's a bit less accessible just because people may not have it installed, but that also means we can leave it out in the open and not have to worry about too many non-contributors joining. :shrug:

**Comment by afiaka87** [comment]
Also a good chance to support open source tools ;)

**Comment by afiaka87** [comment]
This got a little too hands on for me actually - if you need to get ahold of me i'll be on github.

**Comment by robvanvolt** [comment]
> 
> 
> Also a good chance to support open source tools ;)

@afiaka87 someone found an option to host the big dataset (up to 1PT - crazy), so we are currently in the preprocessing again, your input would still be very helpful! :)

**Comment by afiaka87** [comment]
> > 
> > 
> > Also a good chance to support open source tools ;)
> 
> @afiaka87 someone found an option to host the big dataset (up to 1PT - crazy), so we are currently in the preprocessing again, your input would still be very helpful! :)

I appreciate that and I'll try to check in from time to time but I really can't offer as much help there and there's a level of formality and organization to GitHub that allows me to be productive.

I don't know. I have a bad taste in my mouth from the way the machine learning community at large seems to use Twitter/Instagram/Discord to talk about open source. I can really only use that very last one (until MS buys it I guess) and by doing so I'm actively encouraging people to post issues to a difficult to search platform with people whose contributions/expertise are more about "clout" or whatever than they are about the actual work because no one wants to get doxxed.

Anyway, I also found myself eager to moderate and that's probably not a very good use of my time and can't be good for my mental health as the channel continues to grow.

I advise you to consider passing the torch to someone else or deleting the channel if you feel similarly. Moderation is real work and not exactly the exciting kind. And while it's fun to see people trickle in with more data - well, I can't train it really. 

I prefer code, issues, and **transparency**. That means no grandiose claims about datasets and how good DALLE-pytorch could be _until_ it's been proven.

People don't realize it, but open source needs public relations too and rarely ever has it. I guess maybe a slightly hidden group of folks is one way to handle that *aghem eleuther* - but it's been my experience that that channel is a bunch of gatekeeping researchers who put the pressure on themselves of dealing with thousands of strangers and...don't want to deal with it at all.

So yeah! Let me know when you all switch over to matrix and I'll consider it! As it stands it's turning into basically the opposite of what I was hoping.

**Comment by m-bain** [comment]
@robvanvolt the discord link seems to be invalid, could I be added?
