### ISSUE TITLE
Cannot load a trained model on generator.py

### ISSUE THREAD

**Issue by uerdenemunkh** [lucidrains/DALLE-pytorch#117]
Some reason I cannot load the trained model on the generator.py to produce images. 

It generates: _**the shape of the transformer has mismatch.**_  Is it possible at somepoint it added extra layer in the transformer or something, or I am just making a mistake on this. 

I used DQVAE2014, 

```
`load_obj = torch.load(str(dalle_path))
dalle_params, vae_params, weights = load_obj['hparams'], load_obj['vae_params'], load_obj['weights']
vae = VQGanVAE1024()

dalle = DALLE(vae=vae,  **dalle_params ).cuda()
dalle.load_state_dict(weights)`
```

thank you for your help

**Comment by lucidrains** [comment]
Hello! I did change the architecture recently, but did minor version bumps. If you remember which version of the library you used when starting training, you can do a pip install for that specific version first

**Comment by lucidrains** [comment]
I should save the lib version along with the model 🤔

**Comment by uerdenemunkh** [comment]
@lucidrains, okay with right version it works. 

Thank you for help as well your cool projects!
