### ISSUE TITLE
Tiny bug in colab notebook

### ISSUE THREAD

**Issue by afiaka87** [lucidrains/DALLE-pytorch#121]
https://colab.research.google.com/drive/1dWvA54k4fH8zAmiix3VXbg95uEIMfqQM#scrollTo=yrFuBoq3AA8D&line=68&uniqifier=1

@lucidrains looks like a few leftovers from the train_dalle.py script made it into the notebook.

## Line 87:

Bug:
`    IMAGE_SIZE = vae_params['image_size']`

Fix:
`    IMAGE_SIZE = vae.image_size`

## Line 164:
Bug:
```
ds = TextImageDataset(
    args.image_text_folder, # line 164
    text_len = TEXT_SEQ_LEN,
    image_size = IMAGE_SIZE
)
```

Fix:
```
image_text_folder = "output" #@param {type: "string"}
# ...
ds = TextImageDataset(
    image_text_folder, 
    text_len = TEXT_SEQ_LEN,
    image_size = IMAGE_SIZE
)
```

**Comment by lucidrains** [comment]
@afiaka87 fixed! 🙏

**Comment by achesson** [comment]
Apologies for the newbie question, I am stuck around the same lines of code-

line 175: gives error 'AssertionError: dataset is empty'
I set IMAGE_TEXT_FOLDER = '/content/birds/text_c10'

What should be the file path for IMAGE_TEXT_FOLDER?

Thank you for any help
