### ISSUE TITLE
Error during running generate.py

### ISSUE THREAD

**Issue by lsl-88** [lucidrains/DALLE-pytorch#132]
I tried running generate.py but it seems to give the following error "TypeError: type object got multiple values for keyword argument 'vae' ". I have initialized the OpenAIDiscreteVAE class in the generate.py script.

**Comment by lucidrains** [comment]
@lsl-88 hmm, have you pulled the latest changes to the file? a full trace would also help!

**Comment by lsl-88** [comment]
@lucidrains Seems that the latest changes has resolved the issues that I have mentioned. Mainly due to vae_params which is 'None' in the generate script. Thanks!
