### ISSUE TITLE
Problems pickling the model

### ISSUE THREAD

**Issue by TheodoreGalanos** [lucidrains/DALLE-pytorch#154]
Hello, 

I seem to be having a problem saving the model. I suspect this is due to the lambda functions used but I'm not sure since the same code worked 1 day ago. Was there anything in a new push that affected this perhaps?

The error I'm getting specifically, I'm training on colab btw.

```
Can't pickle local object 'TorchGraph.hook_torch_modules.<locals>.backward_hook'
```

**Comment by janEbert** [comment]
Probably related to #155
