### ISSUE TITLE
Captions Showing <|endoftext|> Token

### ISSUE THREAD

**Issue by afiaka87** [lucidrains/DALLE-pytorch#159]
I'm getting this with the CUB dataset from the colab notebook. The  "<|endoftext|>" string is visible in all captions.

`this white bird with primaries and secondaries that fade from gray to white has a wide wingspan and a crayon orange beak ..<|endoftext|>`

Don't _think_ i had this behavior with my pull request but that sounds like it's touching the same place so I'll have a look and see if it's something I did.

**Comment by afiaka87** [comment]
Ah - I see this was intentional. I guess we could do a in the decoder? Or do we want to keep it in the output?

`.replace("<|endoftext|>", "")`

**Comment by lucidrains** [comment]
Oh yup, I added that so the last token in the text actually gets trained

Hmm, we can just do a replace on decode in the simple tokenizer, I'll get around to it soon

**Comment by lucidrains** [comment]
@afiaka87 ok, should be fixed now!

**Comment by afiaka87** [comment]
> Oh yup, I added that so the last token in the text actually gets trained

Yikes - it wasn't until now? Glad you caught that.
