### ISSUE TITLE
What's with the snails?

### ISSUE THREAD

**Issue by afiaka87** [lucidrains/DALLE-pytorch#162]
The snails on the README have always been curious to me. I wasn't around when that was produced - but it's definitely not a result any of us have been even close to producing yet. What's the story there? Was it made with this repository?

**Comment by afiaka87** [comment]
As it stands, it is perhaps a bit misleading as to the current state of things. Unless there's a snail checkpoint out there I'm unaware of...

**Comment by TheodoreGalanos** [comment]
They are taken from OpenAI's blog post afaik.

**Comment by afiaka87** [comment]
Why the hell are they on here then?

**Comment by afiaka87** [comment]
Sorry - I come more from the perspective that _not everyone_ here is a researcher (or maybe it's just me?).

For non-researchers, the distinction between the name of the trained system/model and the name of the _architecture_ used to train that system is confusing. That we choose to name these efforts _after_ the architecture while OpenAI is happy to use the architecture's name to refer to just, sort of, either one of them, is misleading. 

It's a distinction that caused much confusion when GPT-Neo hit the front page of hacker news (largely software engineers, not researchers, in my experience). In terms of open source "PR", or whatever, I assume they lost at least one potential open source contributor that day because of how misleading it felt. The top comment was a disclaimer.

**Comment by lucidrains** [comment]
@afiaka87 hmm, i had no intent on deceiving, its just the image being used by media outlets for DALL-E

I've updated it with Kobiso's results, which I find equally impressive
