### ISSUE TITLE
End tokens visible on wandb when resuming the model

### ISSUE THREAD

**Issue by TheodoreGalanos** [lucidrains/DALLE-pytorch#164]
I'm not entirely sure this is a bug, just wondering. I get the output below on wandb on my current run, which is my first run resuming from a previous checkpoint.

Is there something wrong, did I brake something and I'm training on the text visible? Or is this something on wandb side somehow?

![image](https://user-images.githubusercontent.com/13436572/113483748-9a261a80-94d7-11eb-941e-d80f05f54584.png)

Best,
Theodore.

**Comment by lucidrains** [comment]
@TheodoreGalanos yess, i added the <eos> token so that the last text token is actually trained to predict something (if it predicts padding, it gets no loss) if you update to 0.8.3, it should remove the endoftext for you!
