### ISSUE TITLE
Loading CLIP weights

### ISSUE THREAD

**Issue by eladrich** [lucidrains/DALLE-pytorch#17]
Hi, 
Really nice repo, amazing that you pulled it off so quickly!
I was wondering whether it would be possible to add support to loading weights from the pretrained CLIP model released by openAI https://github.com/openai/CLIP?

**Comment by lucidrains** [comment]
@eladrich Hey Eladrich! I don't have any plans on supporting since their repository is already in pytorch and well documented!

**Comment by lucidrains** [comment]
Why not just use what they have?

**Comment by eladrich** [comment]
I might be missing something but it looks like they only released their model in `TorchScript`, which is kind of annoying to extend and train.

**Comment by lucidrains** [comment]
@eladrich oh wow, yea, I think you are right..

**Comment by lucidrains** [comment]
@eladrich couldn't you still summarize the model and just reconstruct it with the public weights?

**Comment by eladrich** [comment]
Hmm, could be, maybe I can try and extract the weights from the `state_dict` and then do the name matching so it can be loaded into a PyTorch module

**Comment by lucidrains** [comment]
@eladrich 💯 💯 💯

**Comment by zlapp** [comment]
@lucidrains @eladrich just saw official CLIP repo was updated with the model [here](https://github.com/openai/CLIP/blob/main/model.py)

**Comment by eladrich** [comment]
Awesome! Thanks for updating!

**Comment by lucidrains** [comment]
@eladrich @zlapp hurray! :D
