### ISSUE TITLE
Shortened/Exclamation Marks in `decoded_text` i.e. caption

### ISSUE THREAD

**Issue by afiaka87** [lucidrains/DALLE-pytorch#171]
@lucidrains Still around?

I'm having some issues where the decoded text in the training sessions seems to be missing words sometimes and always has a "!" prepended to it.

I'm running with `TEXT_SEQ_LEN=80` to try and shave off some VRAM.

For instance -

> !picture of pizza

instead of 

> a picture of pizza

edit:

Seems to still be an issue with the default `TEXT_SEQ_LEN=256` as well. 
![Screenshot from 2021-04-06 16-42-38](https://user-images.githubusercontent.com/3994972/113781998-206c7780-96f7-11eb-954c-1e056260e030.png)
![Screenshot from 2021-04-06 16-43-29](https://user-images.githubusercontent.com/3994972/113782079-3c701900-96f7-11eb-8898-7aa0e22e051a.png)

**Comment by afiaka87** [comment]
Seems setting `add_start=True` at least prevents it from removing the first word. 

`tokenized_text = tokenize(description, self.text_len, add_start=True,truncate_text=args.truncate_captions).squeeze(0)`

Still getting the exclamation mark however.

**Comment by lucidrains** [comment]
@afiaka87 crap, thanks for catching this! https://github.com/lucidrains/DALLE-pytorch/releases/tag/0.9.5

**Comment by afiaka87** [comment]
@lucidrains no problem! Thanks for the quick fix
