### ISSUE TITLE
OpenAIDiscreteVAE No such file or directory: '/root/.cache/dalle/tmp.encoder.pkl'

### ISSUE THREAD

**Issue by shannonphu** [lucidrains/DALLE-pytorch#177]
Hi,

I was trying to load the pretrained OpenAIDiscreteVAE in Colab and for some reason I keep getting this error about it not being found. Does anyone know why this happens?

Code ran in [Colab](https://colab.research.google.com/drive/1TfwZzJewsMSfLRcbvvnTJMZWgeRE6kUt?usp=sharing):
```
!pip install git+https://github.com/lucidrains/DALLE-pytorch.git

from dalle_pytorch import OpenAIDiscreteVAE
vae = OpenAIDiscreteVAE()
```

Error message:
```
/usr/local/lib/python3.7/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.4) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-2-0d2a716cee22> in <module>()
      1 from dalle_pytorch import OpenAIDiscreteVAE
      2 
----> 3 vae = OpenAIDiscreteVAE()

1 frames
/usr/local/lib/python3.7/dist-packages/dalle_pytorch/vae.py in __init__(self)
     94         super().__init__()
     95 
---> 96         self.enc = load_model(download(OPENAI_VAE_ENCODER_PATH))
     97         self.dec = load_model(download(OPENAI_VAE_DECODER_PATH))
     98 

/usr/local/lib/python3.7/dist-packages/dalle_pytorch/vae.py in download(url, filename, root)
     73         return download_target
     74 
---> 75     with urllib.request.urlopen(url) as source, open(download_target_tmp, "wb") as output:
     76         with tqdm(total=int(source.info().get("Content-Length")), ncols=80) as loop:
     77             while True:

FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/dalle/tmp.encoder.pkl'
```

**Comment by robvanvolt** [comment]
Maybe its regarding your current working folder, you are working from .cache... i would git clone the repository to your standard dev folder /home/yourusername/dev or whatever, and then run setup.py - then the open-ai should automatically be set as the transformer.

training can be started this way:
`python train_dalle.py --image-text-folder myimagetextfolder`

**Comment by afiaka87** [comment]
I've had this issue as well actually. I'll see if i can find the bug.
@shannonphu

**Comment by afiaka87** [comment]
@shannonphu I think I fixed the issue here https://github.com/lucidrains/DALLE-pytorch/pull/178

need to test it first though.

**Comment by shannonphu** [comment]
@afiaka87 Thank you for following up! I will wait for the latest change to test it out.

**Comment by lucidrains** [comment]
@shannonphu Hi Shannon! Give 0.9.6 a try, it should fix your problem! https://github.com/lucidrains/DALLE-pytorch/commit/6a9f76286ee33d283f4581bd96716e78040d3b48

**Comment by shannonphu** [comment]
Awesome! I tried it out and it works now, thank you so much!
