### ISSUE TITLE
stage 3 shape/dimension issues

### ISSUE THREAD

**Issue by afiaka87** [lucidrains/DALLE-pytorch#185]
Edit: Okay - I have zero clue why this is happening but at this point can only assume that it has to do with using CUDA 11 and sparse attention. I've disabled literally everything - including FusedAdam and cpu_offload, and I even just reinstalled deepspeed but this issue persists. 

Wouldn't be the first time I had strange errors because of a somehow borked CUDA install either...

On the other hand, the issue does at least seem quite coincidentally related to the linked deepspeed issue. So I guess I'll leave this up until I know more.

Original post:

Perhaps it has to do with this: 
https://github.com/microsoft/DeepSpeed/issues/828

> When enabling deepspeed stage 3 and using their "FusedAdam" optimizer (the super fast CPU one) instead of passing in the normal Adam optimizer, I get the following stacktrace:
> 
> ```bash
> Traceback (most recent call last):
>   File "train_dalle.py", line 331, in <module>
>     loss = distr_dalle(text, images, return_loss = True)
>   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 914, in forward
>     loss = self.module(*inputs, **kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/root/DALLE-pytorch/dalle_pytorch/dalle_pytorch.py", line 459, in forward
>     image = self.vae.get_codebook_indices(image)
>   File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
>     return func(*args, **kwargs)
>   File "/root/DALLE-pytorch/dalle_pytorch/vae.py", line 152, in get_codebook_indices
>     _, _, [_, _, indices] = self.model.encode(img)
>   File "/root/.local/lib/python3.8/site-packages/taming_transformers-0.0.1-py3.8.egg/taming/models/vqgan.py", line 54, in encode
>     quant, emb_loss, info = self.quantize(h)
>   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/root/.local/lib/python3.8/site-packages/taming_transformers-0.0.1-py3.8.egg/taming/modules/vqvae/quantize.py", line 42, in forward
>     torch.sum(self.embedding.weight**2, dim=1) - 2 * \
> IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
> ```

> The input_mask that we currently support in our implementation must have this shape (batch_size, 1, 1, sequence_length). This means that the mask can be different for different input.

**Comment by afiaka87** [comment]
In the issue - they are working on a solution which allows you to pass in a custom shape. I think that might help. Alternatively - is it possible to work with the expected shape somehow?

**Comment by afiaka87** [comment]
All I know for sure is that deepspeed stage 3 *with cpu offload* (and literally nothing else) worked for me - and then somehow deepspeed stage 3 broke itself in a permanent way.

I've tried several things:

- merge the pull request mentioned in the deepspeed issue into my PR 
- is it a dataset problem? switch to CUB because many have successfully trained with it
- am i certain my training code is identical otherwise? `git checkout .` from main and add _back_ in _just_ this config:
```
    "zero_optimization": {
        "stage": 3,
        "cpu_offload": True,
    },
```
But the problem persists - even though IT WORKED - this exact same config worked before I ever decided to enable FusedAdam. After that - it won't go away at all until I just straight up `git checkout train_dalle.py` to disable zero_optimization alltogether.

I haven't yet tried the most obvious fix - use microsoft's main repo with a version of CUDA 10.1 instead - but I unfortunately don't have the ability to reconfigure my install like that and would have to just set up a new instance just to test this problem which may in fact just sort of go away for whatever reason. 

So if anyone can try running stage 3 with FusedAdam on CUDA 10.1 on a V100 - have at it. I'll just say, at this point, I'm glad we're supporting horovod as well.

**Comment by afiaka87** [comment]
I have at least verified that the problem was indeed caused by running "fused_adam" on the CPU with stage 3.

Switch to stage 2 with `cpu_offload = True` results in a CUDA out of memory error - not sure why. 

However, if you still want to use FusedAdam (it should still be a good deal faster than torch.optim.Adam - correct?) then you can disable cpu_offload and stick with stage 2:

```python

deepspeed_utils.check_batch_size(BATCH_SIZE)
deepspeed_config = {
    "zero_optimization": {
        "stage": 2,
    },
    "optimizer": {
        "type": "Adam",
        "params": {
            "lr": LEARNING_RATE,
        },
    },
    'train_batch_size': BATCH_SIZE,
    'gradient_clipping': GRAD_CLIP_NORM,
    'fp16': {
        'enabled': args.fp16,
    },
}

(distr_dalle, opt, dl, scheduler) = deepspeed_utils.maybe_distribute(
    args=args,
    model=dalle,
    optimizer=None,
    model_parameters=dalle.parameters(),
    training_data=ds if args.deepspeed else dl,
    lr_scheduler=scheduler if LR_DECAY else None,
    config_params=deepspeed_config,
)
avoid_model_calls = args.deepspeed and args.fp16
```

**Comment by janEbert** [comment]
May also be related to [external parameters in DeepSpeed](https://deepspeed.readthedocs.io/en/latest/zero3.html#registering-external-parameters).
I've [opened an issue asking about these](https://github.com/microsoft/DeepSpeed/issues/930) but haven't gotten an answer that.

Since you're getting an error, I'm assuming these are problems with external parameters finally showing up. :)

**Comment by janEbert** [comment]
DeepSpeed 0.3.15 now automatically detects external parameters but I'll #207 adds manual external parameter registration anyway.
