### ISSUE TITLE
Can I use Chinese text？

### ISSUE THREAD

**Issue by LIMr1209** [lucidrains/DALLE-pytorch#197]
Can I use Chinese text？

**Comment by lucidrains** [comment]
@LIMr1209 sure! planning on supporting huggingface tokenizers, which should be able to do Chinese!

**Comment by LIMr1209** [comment]
@lucidrains Well, thank you

**Comment by lucidrains** [comment]
@LIMr1209 do you want to give https://github.com/lucidrains/DALLE-pytorch#custom-tokenizer a try?

**Comment by LIMr1209** [comment]
![image](https://user-images.githubusercontent.com/37957822/114820455-95276c00-9df1-11eb-9ba9-730f0d76e6b3.png)

**Comment by LIMr1209** [comment]
The text data I prepared is like this

**Comment by LIMr1209** [comment]
First vae, then dalle, right?

**Comment by lucidrains** [comment]
@LIMr1209 ohh, you need to tokenize your text first (create a chinese vocabulary)

**Comment by lucidrains** [comment]
oh, actually, it seems there's already a pretrained one `BertTokenizer.from_pretrained('bert-base-chinese')` - I'll see what I can do tomorrow

**Comment by LIMr1209** [comment]
How can I find it bpe.json

**Comment by lucidrains** [comment]
@LIMr1209 it's ok, i'll take care of it by wiring up one that is already trained, and you can just pass in a flag like `--use-chinese`

**Comment by LIMr1209** [comment]
Okay, thank you. Wait for you tomorrow

**Comment by lucidrains** [comment]
@LIMr1209 let me know if this works for you! https://github.com/lucidrains/DALLE-pytorch/tree/0.10.2#chinese

**Comment by LIMr1209** [comment]
![image](https://user-images.githubusercontent.com/37957822/114961818-22bf9600-9e9c-11eb-8568-2f18bda71577.png)
@lucidrains bug

**Comment by LIMr1209** [comment]
Latest code

**Comment by lucidrains** [comment]
@LIMr1209 https://github.com/lucidrains/DALLE-pytorch/commit/c47431c607763812c6b523054454001fdfeaef2c
