### ISSUE TITLE
Ready to use?

### ISSUE THREAD

**Issue by Thierryonre** [lucidrains/DALLE-pytorch#2]
Am I right in assuming this repo is not ready for generating images?

**Comment by lucidrains** [comment]
Lol no, it's just a first draft, but I reckon within a week or two, should be able to start training on something small, maybe 64x64 images

**Comment by lucidrains** [comment]
Come help out!

**Comment by Thierryonre** [comment]
I'd absolutely love to but I don't have the skills :''''(

**Comment by yugaljain1999** [comment]
> Come help out!

I am ready to help you @lucidrains I am really interested in this and want to work with you.
Regards!
