### ISSUE TITLE
 Can input multiple text？

### ISSUE THREAD

**Issue by changrannn** [lucidrains/DALLE-pytorch#200]
When run generate.py,can input text more than one ? Thank you！

**Comment by lucidrains** [comment]
https://github.com/lucidrains/DALLE-pytorch/commit/ce0c8929075fd793367db3b874accae140818ca1 let me know if that works!

**Comment by changrannn** [comment]
OK, Thank you!

**Comment by changrannn** [comment]
It may need some times. 
Dataset is CUB ,epoch is 10 . The image generated after I trained the model:
https://user-images.githubusercontent.com/76522213/115026772-77dbc600-9ef5-11eb-99b5-af5e5e5b2ed4.png

The sample :
https://user-images.githubusercontent.com/76522213/115027077-d739d600-9ef5-11eb-9257-0038df97937a.jpg

Can you give me some advice?

**Comment by lucidrains** [comment]
@changrannn follow what kobiso did! https://github.com/lucidrains/DALLE-pytorch/discussions/131
