### ISSUE TITLE
Hugging Faces Tokenizers Produce Random Whitespace

### ISSUE THREAD

**Issue by afiaka87** [lucidrains/DALLE-pytorch#203]
> By default, the ByteLevel BPE might include whitespaces in the produced tokens. If you don’t want the offsets to include these whitespaces, then this PostProcessor must be used.

This post-processor takes care of trimming the offsets.

https://huggingface.co/docs/tokenizers/python/latest/api/reference.html#tokenizers.processors.ByteLevel

**Comment by robvanvolt** [comment]
What are the advantages of BPE huggingface in comparison to the default tokenizer?

**Comment by lucidrains** [comment]
@afiaka87 i think i may just switch to using https://github.com/VKCOM/YouTokenToMe instead - it's much simpler and faster

**Comment by afiaka87** [comment]
Do leave the hugging faces one in as well - I'm using it currently and can add the post processing step later. But yes, More options please! Thanks @lucidrains

**Comment by lucidrains** [comment]
@afiaka87 i tried adding the post processor but it didn't do anything :(

**Comment by lucidrains** [comment]
@afiaka87 I fixed this issue with the `youtokentome` library (it works great)

if you want to still try to debug the huggingface version, just pass in `--hug`, but i'm going to mark this as resolved

**Comment by afiaka87** [comment]
Yep no worries thanks @lucidrains
