### ISSUE TITLE
('full', 'axial_row', 'axial_col', 'conv_like')  works, but uses more memory than just 'full'

### ISSUE THREAD

**Issue by afiaka87** [lucidrains/DALLE-pytorch#213]
_# Original post by @kobiso https://github.com/lucidrains/DALLE-pytorch/discussions/131#discussioncomment-640446_

**Go give them a rocket emoji!**

## Attention type ('full', 'axial_row', 'axial_col', 'conv_like') works
- Above experiment is trained with attention type ('full', 'sparse'), where DeepSpeed sparse attention gives advantages of memory usage and training speed.
- However, OpenAI's DALL-E includes row, column, convolutional attention to the model as below.
![image](https://user-images.githubusercontent.com/12422441/115570418-0dfa5c80-a2f9-11eb-8fe2-31ab3db11714.png)
- Thankfully, these attention types are implemented as in [README](https://github.com/lucidrains/DALLE-pytorch#sparse-attention).
- So, I did an experiment with attention type ('full', 'axial_row', 'axial_col', 'conv_like').

### Experimental setting
- DALLE-pytorch version: [0.7.2](https://github.com/lucidrains/DALLE-pytorch/releases/tag/0.7.2)
- Attention type: ('full', 'axial_row', 'axial_col', 'conv_like')
- Batch size: 32 * 7 (gpus)
- Others are the same as https://github.com/lucidrains/DALLE-pytorch/discussions/131#discussion-3296648
- Pretrained model is in https://github.com/kobiso/DALLE-reproduction

### Computational cost
- **Training speed**: training speed was decreased by 38% compared to ('full', 'sparse')
- **Memory consumption**: had to reduce from 110 ('full', 'sparse') to 32 ('full', 'axial_row', 'axial_col', 'conv_like') per gpu

### Training log
![image](https://user-images.githubusercontent.com/12422441/115573107-74807a00-a2fb-11eb-8982-340318bafddb.png)

### Results
- I feel like ('full', 'sparse') is little better than ('full', 'axial_row', 'axial_col', 'conv_like') on generation performance.
- But still, ('full', 'axial_row', 'axial_col', 'conv_like') does work 👍 

![image](https://user-images.githubusercontent.com/12422441/115573261-8eba5800-a2fb-11eb-9cf0-fc0b9eecb652.png)

_Originally posted by @kobiso in https://github.com/lucidrains/DALLE-pytorch/discussions/131#discussioncomment-640446_

**Comment by lucidrains** [comment]
@afiaka87 nice, glad to hear it is working! :)

**Comment by afiaka87** [comment]
same here! sparse would be fantastic and hopefully it starts working more consistently with the zero infinity stuff - but this works too in terms of memory savings.

**Comment by afiaka87** [comment]
@kobiso @lucidrains can either of you speak as to why the axial and conv-like attention seem to require so much more memory than using just 'full' on its own?

**Comment by lucidrains** [comment]
ohh I understand why, I'll get it fixed by Friday!

**Comment by TheodoreGalanos** [comment]
> 
> 
> ohh I understand why, I'll get it fixed by Friday!

does that mean I should wait for training a new model (i.e. breaking changes?) or is it safe to do so :)

**Comment by lucidrains** [comment]
@TheodoreGalanos it won't be breaking! It'll simply be more memory efficient attention , train away :)

**Comment by afiaka87** [comment]
Great work @lucidrains
