### ISSUE TITLE
Permission denied for CUB dataset

### ISSUE THREAD

**Issue by lsh950919** [lucidrains/DALLE-pytorch#218]
![화면 캡처 2021-04-27 083606](https://user-images.githubusercontent.com/52195373/116163957-c37f4280-a733-11eb-9d4a-e596b09465d4.png)

I was trying to go through the training process in colab but when I try downloading the CUB dataset it shows Permission denied message.

I didn't have any issues like this yesterday, so this is a bit confusing to me.

Any ideas?

**Comment by afiaka87** [comment]
This unfortunately happens from time to time with any publically shared link from a Drive account that gets downloaded by a lot of people. @lucidrains you may need to re-host I guess.

**Comment by afiaka87** [comment]
You can use these links instead for now. They expire tomorrow.

https://www.dropbox.com/s/7dx4mp2vk4uksus/birds.zip

https://www.dropbox.com/s/vc9y3do9vegzb1v/CUB_200_2011.tgz


@lsh950919

**Comment by lucidrains** [comment]
@afiaka87 thanks :)

@lsh950919 i've updated the gdrive links in the colab, do you want to retry them?
