### ISSUE TITLE
Use OpenAIDiscreteVAE as pretrained model

### ISSUE THREAD

**Issue by richcmwang** [lucidrains/DALLE-pytorch#219]
I notice the forward function in the `OpenAIDiscreteVAE` class is not implemented.  I am interested in using this model as a pretrained model and train it on a medical dataset.  What is the best approach to achieve this?  

1. implement the forward function
2. Is it possible to initialize the parameters for `DiscreteVAE` class such that we can load the Openai discrete vae model in with `load_state_dict( )`? 

Any suggestion is welcome!

**Comment by lucidrains** [comment]
@richcmwang hmm, I don't have any plans to do so. I think the onus would be on OpenAI to provide that

**Comment by richcmwang** [comment]
Understood.  A question on the second point: For the current `DIscreteVAE` code, is there a way to load `OpenAIDiscreteVAE` encoder/decoder in?  Or the two models have a different design so loading pretrained is not feasible?

**Comment by lucidrains** [comment]
@richcmwang there are some slight differences, so it won't be loadable, unfortunately. one thing to note is that it is coming to light that the VQVAE from Taming Transformers is actually much better than the OpenAI one (despite the latter's scale)

https://github.com/CompVis/taming-transformers Their repository should be more approachable for training your own VAE (or fine tuning your data from their checkpoints)

**Comment by richcmwang** [comment]
Thanks for pointing to the taming-transformers.   The reconstruction images contain a lot more details! Can the VQVAE pass directly into your `train_dalle.py` through `--vae-path`?

**Comment by lucidrains** [comment]
@richcmwang oh oops, never documented, but you just have to omit the `--vae-path` and pass in `--taming` to use the trained taming VQVAE

there is an issue open for using your own trained VQVAE, and i'll have to put some thought into that before writing that feature out in code

**Comment by richcmwang** [comment]
Thanks!  will give it a try!
