### ISSUE TITLE
Generate 1024*1024 image

### ISSUE THREAD

**Issue by talha-khalid-qureshi** [lucidrains/DALLE-pytorch#221]
Hi, Thanks for sharing this wonderful project. I am interested in to generate 1024*1024 resolution image against text. Please guide me which parameters i have to change for getting such results. And also guide which step i have to follow to achieve text to image by using custom data from scratch.

**Comment by DanielSJRP** [comment]
teste

**Comment by lucidrains** [comment]
i'm afraid 1024 x 1024 will be out of reach - the best you'll be able to do is 512 x 512, and that will be with training 1024 image tokens using the Taming Transformer VQ-VAE
