### ISSUE TITLE
RuntimeError: dlsym unable to load function

### ISSUE THREAD

**Issue by EnvironmentalEngineer** [lucidrains/DALLE-pytorch#23]
Hi when I was running the example code about CLIP, I got the following error. It seems to me something of triton is not working. I went through a lot of websites but there were not many discussions about this. Could anyone please show me how to fix this? Many thanks!

RuntimeError                              Traceback (most recent call last)
<ipython-input-3-452d2849b6bc> in <module>
     20 mask = torch.ones_like(text).bool().to(device)
     21 
---> 22 loss = clip(text, images, text_mask = mask, return_loss = True)
     23 loss.backward()

~/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

~/anaconda3/lib/python3.7/site-packages/dalle_pytorch/dalle_pytorch.py in forward(self, text, image, text_mask, return_loss)
    213         image_emb += self.visual_pos_emb(torch.arange(image_emb.shape[1], device = device))
    214 
--> 215         enc_text = self.text_transformer(text_emb, mask = text_mask)
    216         enc_image = self.visual_transformer(image_emb)
    217 

~/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

~/anaconda3/lib/python3.7/site-packages/dalle_pytorch/transformer.py in forward(self, x, **kwargs)
    200 
    201     def forward(self, x, **kwargs):
--> 202         return self.layers(x, **kwargs)

~/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

~/anaconda3/lib/python3.7/site-packages/dalle_pytorch/reversible.py in forward(self, x, **kwargs)
    137 
    138         for (f, g), (f_args, g_args) in layers_and_args:
--> 139             x = x + f(x, **f_args)
    140             x = x + g(x, **g_args)
    141         return x

~/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

~/anaconda3/lib/python3.7/site-packages/dalle_pytorch/transformer.py in forward(self, x, **kwargs)
     34 
     35     def forward(self, x, **kwargs):
---> 36         return self.fn(self.norm(x), **kwargs)
     37 
     38 class GEGLU(nn.Module):

~/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

~/anaconda3/lib/python3.7/site-packages/dalle_pytorch/transformer.py in forward(self, x, mask)
    158                 attn_mask[ind, ind] = 0.
    159 
--> 160         out = self.attn_fn(q, k, v, attn_mask = attn_mask, key_padding_mask = key_pad_mask)
    161         out = rearrange(out, 'b h n d -> b n (h d)')
    162         out = self.to_out(out)

~/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

~/anaconda3/lib/python3.7/site-packages/deepspeed/ops/sparse_attention/sparse_self_attention.py in forward(self, query, key, value, rpe, key_padding_mask, attn_mask)
    150 
    151         # attention scores
--> 152         attn_output_weights = sparse_dot_sdd_nt(query, key)
    153         attn_output_weights = sparse_softmax(
    154             attn_output_weights,

~/anaconda3/lib/python3.7/site-packages/deepspeed/ops/sparse_attention/matmul.py in __call__(self, a, b)
    744                                  db_packs,
    745                                  self.bench,
--> 746                                  time_db)
    747         self.time_c = time_c[0]
    748         self.time_da = time_da[0]

~/anaconda3/lib/python3.7/site-packages/deepspeed/ops/sparse_attention/matmul.py in forward(ctx, a, b, trans_a, trans_b, trans_c, mode, spdims, block, c_lut, c_num_locks, c_width, c_packs, c_bench, c_time, da_lut, da_num_locks, da_width, da_packs, da_bench, da_time, db_lut, db_num_locks, db_width, db_packs, db_bench, db_time)
    548                                     c_packs,
    549                                     c_bench,
--> 550                                     c_time)
    551         # save for backward
    552         ctx.save_for_backward(a, b)

~/anaconda3/lib/python3.7/site-packages/deepspeed/ops/sparse_attention/matmul.py in _sdd_matmul(a, b, trans_a, trans_b, trans_c, spdims, block, luts, num_locks, widths, packs, bench, time)
    226                                       width - off_width),
    227                                   AS0],
--> 228                                  bench=bench)
    229                 total = total + current if bench else None
    230             time[0] = total

~/anaconda3/lib/python3.7/site-packages/triton/kernel.py in __call__(self, *args, **kwargs)
     84     params = pack(self.tys, *[x.data_ptr() if isinstance(x, torch.Tensor) else x for x in args])
     85     torch.cuda.synchronize()
---> 86     torch.ops.triton.launch_kernel(self.op_id, device, params)

RuntimeError: dlsym unable to load function

**Comment by lucidrains** [comment]
@EnvironmentalEngineer I think it's because you are trying to use `SparseAttention` and your `triton` package didn't install correctly

I did hint that the installation process was not going to be smooth sailing ;)

**Comment by lucidrains** [comment]
@EnvironmentalEngineer Hello there! I had sparse attention turned on by default for clip by accident, it should be fixed in the latest version!

**Comment by EnvironmentalEngineer** [comment]
> @EnvironmentalEngineer Hello there! I had sparse attention turned on by default for clip by accident, it should be fixed in the latest version!

Hi, thanks for replying. I reinstalled the dalle-pytorch package. This time there was no sparse attention comment however I still got the same error. I think it is a problem with triton. May I know if there is any way that I can skip using triton? Thanks!

**Comment by EnvironmentalEngineer** [comment]
Problem solved! I just used the repo code instead of the pip install command.
