### ISSUE TITLE
Hardcoded hyper-parameters?

### ISSUE THREAD

**Issue by mehdidc** [lucidrains/DALLE-pytorch#232]
Hi,

Is there a specific reason why  the optimization hyper-parameters are hardcoded in https://github.com/lucidrains/DALLE-pytorch/blob/main/train_dalle.py#L70 instead of being in the CLI arguments ?
if not, I could do a PR where I push them into the arguments to make the full hyper-parameters configurable in one place.

**Comment by robvanvolt** [comment]
Agree on that, e.g. attn_types need to be added to the DALLE-dict on every new release!:)

**Comment by lucidrains** [comment]
@mehdidc i can take care of that! i'm planning on migrating the argparse library over to https://github.com/pallets/click

**Comment by mehdidc** [comment]
@lucidrains Ah cool, thanks ! :)

**Comment by afiaka87** [comment]
> @mehdidc i can take care of that! i'm planning on migrating the argparse library over to https://github.com/pallets/click

Nice this will make working with W&B's hyperparameter tuning much simpler as they use the CLI args to change the hyperparameters each run.

**Comment by lucidrains** [comment]
i found something even better https://github.com/tiangolo/typer

**Comment by lucidrains** [comment]
author of the famous FastAPI

**Comment by lucidrains** [comment]
Nvm, it can't do mutually exclusive options :(

**Comment by lucidrains** [comment]
@mehdidc aw, i can't use click either, because of how we dynamically add arguments for distributed settings

ok, i've argparsed everything! https://github.com/lucidrains/DALLE-pytorch/commit/0923560378dccc7dda18b4c3f97b38c561cbd9f0 let me know if that works for you!

**Comment by mehdidc** [comment]
Thanks a lot @lucidrains ! I think the only thing still missing is `attn_types` that @robvanvolt mentioned :D

**Comment by mehdidc** [comment]
I added a PR for `attn_types`  in #236
