### ISSUE TITLE
How can I resume a training started with deepspeed ?

### ISSUE THREAD

**Issue by rom1504** [lucidrains/DALLE-pytorch#235]
`--dalle_path=dalle-ds-cp/global_step1501/mp_rank_00_model_states.pt` doesn't seem to cut it
It's complaining about a missing weights key

**Comment by rom1504** [comment]
is https://github.com/lucidrains/DALLE-pytorch/pull/222 needed ?

**Comment by rom1504** [comment]
dalle.pt is also not going saved in deepspeed mode, so there is no way to resume if using deepspeed
any insight into that @afiaka87 ? it seems you got it to work

**Comment by afiaka87** [comment]
as discussed on discord - I'll look into this today. @janEbert has implied the PR is somewhat complete - so I'll give it a shot and see if we can't go ahead and merge.

**Comment by janEbert** [comment]
Hey, this is somewhat convoluted... I implemented it so it's completely backward-compatible. Just give `--dalle_path dalle.pt` and the rest will be figured out by itself.
We get the DeepSpeed checkpoint to load from the name of the non-DeepSpeed checkpoint passed in.

**Comment by rom1504** [comment]
When I tried training with deep speed the dalle.pt file was not saved either.
I can try again if there were some fixes.

**Comment by janEbert** [comment]
The idea was that all the command line arguments people already use "just work". In a perfect world, the `dalle.pt` file is not used at all. It's also going to cause trouble to have that unrelated file connected to the DeepSpeed checkpoints as that means you have to keep it together with the DeepSpeed checkpoints at all times. Finally, users trying to load the `dalle.pt` file without DeepSpeed active will see errors, so there's another source of confusion.

However, I did realise a mistake there (it was still too early to not save standard checkpoints) and why we still need them. So #241 fixes that. If you don't want to wait till it's merged, start a run without DeepSpeed with the parameters you'd use and wait till the first checkpoint is saved. At that point, you can resume with DeepSpeed as explained.

**Comment by rom1504** [comment]
so this is already working actually, just need to not put the .pt in --dalle-path arg
