### ISSUE TITLE
Bring back Epicmafia

### ISSUE THREAD

**Issue by chesse20** [lucidrains/DALLE-pytorch#258]
i cannot play epic mafia the website is down can you plase fix also how do i download this program all there is is a bunch of python lines of code and 2 collab notebooks and i don't know how to put them onto my computer okay thanks for bringing epicmafia back online in advance

**Comment by lucidrains** [comment]
@chesse20 i'll work on it soon, can you all elect a moderator or admin? someone who isn't going to go crazy this time?

**Comment by lucidrains** [comment]
@chesse20 not the appropriate place to discuss this, but can you all get together and elect an admin who won't destroy the site this time?

**Comment by lucidrains** [comment]
@chesse20 i'll look into bringing back the site this weekend..
