### ISSUE TITLE
Breaking change in model

### ISSUE THREAD

**Issue by rom1504** [lucidrains/DALLE-pytorch#260]
One of https://github.com/lucidrains/DALLE-pytorch/commit/27079ddc84cf1fcefb9146032f36f3fe3fa947de https://github.com/lucidrains/DALLE-pytorch/commit/f794ba62efcfee23e4d9a2e6fa93b532fd50af56 https://github.com/lucidrains/DALLE-pytorch/commit/e8c2d9948196d6e7d3911767d533dd01f11ea821 introduced a change that make models trained before these commits not to work anymore.
Could that be fixed @lucidrains ?

**Comment by lucidrains** [comment]
@rom1504 oh oops, do you want to see if https://github.com/lucidrains/DALLE-pytorch/commit/a51985af3281966ce26a01b191f8643f7c6ceae2 fixes things?

**Comment by rom1504** [comment]
I confirm that solves the issue.
Thanks for the quick fix!
