### ISSUE TITLE
`DALLE-pytorch` as a project name

### ISSUE THREAD

**Issue by afiaka87** [lucidrains/DALLE-pytorch#267]
@lucidrains 

I personally don't mind too much about this and have gotten _very_ used to holding down my shift key when typing out `DALLE`. 

Having said that, some users in the discord mentioned concern over the name of the repository being "DALLE-pytorch" when we may be incorporating other concepts from CogView and indeed already support using a VQGAN (unlike OpenAI). 

(btw, _are_ we going to add concepts like the self-rerank and others listed here https://github.com/lucidrains/DALLE-pytorch/issues/263 ?)

I'm here for the long haul - I very much enjoy working on your codebases because they are clean and I trust you a good deal after the past 6 odd months of contributions. But I guess there was concern that "CogView" would become similarly popular once they release their weights. I don't disagree and indeed I intend to work on both codebases if that's interesting to me. This is how open source is meant to work in my view and I think we're aligned on that. 

One suggestion was to create a new repository for general text-to-image with transformers. This could include several of the architectures you've recreated including big-sleep, deep-daze, DALLE-pytorch, and CogView. That's obviously quite a lot of work and I'm definitely not volunteering, so yeah. The general link between them is definitely pytorch (currently anyway), so perhaps something like `text-to-img-pytorch`?

Anyway I don't have much of a stake in this unfortunately, just voicing some concerns from the "community" we sorta have.

**Comment by rom1504** [comment]
My opinion is that Dall-e is known and will stay known, it's a simple name and since openai won't release any code it'll stay available.
Cogview is pretty similar so I think its features fit here.
So I think keeping that name is fine.
If there is a super good other name why not rename though.

**Comment by afiaka87** [comment]
> If there is a super good other name why not rename though.

Extra work/breaking backwards compatibility/annoying users of the pip package to name a few

**Comment by afiaka87** [comment]
Anyway i'm gonna close this in a bit - discord folks - your voice isn't exactly heard on the discord. Please reach out here with your concerns! We don't bite!
