### ISSUE TITLE
deepspeed only uses a single GPU

### ISSUE THREAD

**Issue by richcmwang** [lucidrains/DALLE-pytorch#279]
I probably have missed something.  After setting args.deepspeed = True (and installation of deepspeed), I seem to start deepspeed.  But the computation only concentrates on a single GPU.  Are there any parameters we need to set?

**Comment by afiaka87** [comment]
@richcmwang 
You will also need to install deepspeed using either the Dockerfile we provide or the the `install_deepspeed.sh`.

Deepspeed should auto-detect your gpus, but you'll need to run the train_dalle.py with the `deepspeed` command instead of `python`:

```sh
deepspeed train_dalle.py --image_text_folder "dir" --taming --deepspeed
```

**Comment by richcmwang** [comment]
Thanks! @afiaka87  I missed the initial deepspeed command and it works now!  I am interested in training deeper depth (e.g. --depth 32, --head 32), but run out of GPU memory.  It seems we need some kind of model parallel.  Is there a straightforward way to do it with a command? Or we have to try something like ZeRO Optimization?

**Comment by richcmwang** [comment]
A follow-up question on training bigger model (depth 32, heads 32). It is achievable with 24 GB x 2 GPUs with batch size 2 with zero-optimization set to stage 1. Each GPU takes almost the entire 24GB.  However, it is not possible on 11 GB x 8 GPUs - out of CUDA memory.  I want to make a guess whether 16GB x 16 could work before trying it (24GB x 8 GPUs will probably work with stage 1), and understand what would be the optimal set-up.

Experiments with heads/depth = 16 and batch size 8 on 11G x 8 GPUs show that with zero-optimization set to stage 1, the 1st GPU takes almost the entire 11G while the rest 7 GPUs takes around 8G out of 11G.  When on stage 2, the 1st GPU load drops to 3.5G while the rest of the GPUs go up 11G briefly, then run out of CUDA memory.  So stage 2 actually does not help in this setup.  Any insight on memory is shifted away from the 1 GPUs and go fairly low?
