### ISSUE TITLE
Support 16k Token Imagenet VQGAN

### ISSUE THREAD

**Issue by afiaka87** [lucidrains/DALLE-pytorch#290]
The 1024 token VQGAN is impressive but can definitely miss some important features at the per-patch scale. This winds up effecting anything "too small" in your picture to be well-represented in the VQGAN. This results in faces with very jarring and abstract features and lots of indecipherable text.

I'm curious if the 16k VQGAN is better in this instance. I've seen it used in the "CLIP+blah" land on eleuther and indeed it does seem to produce better results than the 1024 token version.

**Comment by afiaka87** [comment]
The patch size for that one is still 16px, right?

**Comment by rom1504** [comment]
I agree it would be useful.
Let's share it along with #192

**Comment by rom1504** [comment]
Yeah the patch size is still 16px with this one

**Comment by rom1504** [comment]
this is done
