### ISSUE TITLE
CogView Released! (But it requires a chinese phone number to download the weights)

### ISSUE THREAD

**Issue by afiaka87** [lucidrains/DALLE-pytorch#306]
https://github.com/THUDM/CogView

**Comment by robvanvolt** [comment]
I have the feeling that this is not the end of the journey... but just the beginning :D

**Comment by robvanvolt** [comment]
I have the feeling that the CogView release is not the end of the journey... but just the beginning :D

**Comment by afiaka87** [comment]
Definitely! Collaboration is fundamental to good science and all this means for me is that we now have another team who has explored the problem fairly well and actually documented and released their weights (unlike OpenAI). 

The knowledge we've accrued over the past several months will be very useful for the replication study which I believe intends to explore not just DALL-E; but advancements made since DALLE as well such as the VQGAN and differing architectures discovered by CogView. 


This is indeed the beginning. Something like this was quite unfathomable just a few years ago and annoyingly concealed by OpenAI. This work will democratize those ideas for any researcher to use; not just those with enough VC funding.

**Comment by afiaka87** [comment]
https://github.com/THUDM/CogView/issues/11

Perhaps this isn't as open of a release as I had thought.

**Comment by johnpaulbin** [comment]
> [THUDM/CogView#11](https://github.com/THUDM/CogView/issues/11)
> 
> Perhaps this isn't as open of a release as I had thought.

Fixed, weights are now available on a torrent.

**Comment by YukiSakuma** [comment]
Anyone could store the model in a mirror link like google drive?

**Comment by johnpaulbin** [comment]
> Anyone could store the model in a mirror link like google drive?

Here you go @YukiSakuma , you can simply wget: `https://the-eye.eu/public/AI/CogView/cogview-base.tar`

My Colab featuring the link is here: https://colab.research.google.com/drive/1Bi2TnSUp2vNiSUhamsNuC4HqkZ2J4WwZ
