### ISSUE TITLE
refactor

### ISSUE THREAD

**Issue by afiaka87** [lucidrains/DALLE-pytorch#309]
We need a refactor. Maybe a redesign (breaking backwards compatibility). The codebase has accrued just a little too much tech debt. Particularly in the `train_dalle.py` and `README.md`

## Training loop
- The training loop needs to be refactored into a function in the style of pytorch lightning. This dramatically improves readability and makes early returns possible which is a cleaner solution than raising an Exception.

## Argument parsing
- All arg-parsing need to be well-consolidated into a single file. Perhaps another file at the root of the repo as it's still something people are going to want to open up quickly.

## Style guide and automatic formatting in CI 
- This one's easy - we need a consistent target format for multiple contributors to target. I like PEP8 but honestly if we just pick one I'll be happy we're using a linter/formatter at all. Alternatives are black/yapf. I could integrate this into Github Actions so that code is automatically formatted upon merge to main.

## Configuration:
- we should provide reasonable defaults `deepspeed_config.json` in a folder at the root called "config" and encourage people to update that file rather than update the `deepspeed_config` variable in Python which is a bit of a hassle to get to and find each time. A comment at the top of each file with a links to:
- https://deepspeed.readthedocs.io/en/latest/schedulers.html # Various (otherwise) undocumented schedulers from DeepSpeed
- https://www.deepspeed.ai/docs/config-json/#zero-optimizations-for-fp16-training # Options specific to zero.

## README.md
 -  The readme is a bit long; but that's alright. I prefer the idea of a single source of truth with documentation; especially one that doesn't require the internet after you've downloaded it e.g. the wiki
 - It just needs a table of contents and a "quick start" at the top. I do like the idea of continuing to give progress updates on the `current best` at the top as well. So let's keep that. taming-transformers has a wonderfully clean README.md with a table of contents which could be used as a basis. 

Feel free to criticize the current design (please be constructive and polite - we're all lazy coders at the end of the day) so we can decide if breaking backwards compatibility for a new design would be worthwhile.

**Comment by rom1504** [comment]
I agree with the main idea, I would advise to try implementing parts of this in small PRs. This has as benefits :
* To avoid big breaking change
* to make sure that's really what you want to do without spending too much time on it
* To make reviews easier

**Comment by rom1504** [comment]
Just one concern. The current style (of train dalle .py) is low abstraction. The benefit of that is it's easy for anyone to read and understand the code. The drawback as you noticed is it doesn't scale to many features and lines of code.
I think it may make sense to add some abstraction with a training class but just make sure not to add too much abstraction and lose the easy to understand property.
That's a trap of this kind of refactoring, let's not fall into it :)

**Comment by johnpaulbin** [comment]
Move this to Discussions 👍

**Comment by janEbert** [comment]
I'm not in favor of moving the DeepSpeed config to a JSON file. JSON simply does not offer what a full programming language does. Just look at the DeepSpeed config and you see how dynamic it is with regards to all the different command line arguments and whatnot. What you could do is split the configuration into a JSON file and override certain config values with the ones we set dynamically; but then you make modifications much harder due to having to keep track of what's being overwritten in the config and what isn't. You'd also have to look into two places to grog the whole config.
We could place a function like `def create_deepspeed_config(batch_size, fp16, [...])` at the top of the file, then people would be able to find the config sooner.

I also agree with @rom1504 – the code is supposed to be readable without abstractions first and foremost as far as I see from @lucidrains' code bases. I do see the option of refactoring the less important functions out of the loop, like:
```python
if i % 100 == 0:
    generate_samples(text, [...])
```

Finally, just a tip, you can actually clone GitHub wikis like a standard repository for offline availability. :)
The link is `<https-repo-url>.wiki.git` (here: https://github.com/lucidrains/DALLE-pytorch.wiki.git).

**Comment by afiaka87** [comment]
> I'm not in favor of moving the DeepSpeed config to a JSON file. JSON simply does not offer what a full programming language does. Just look at the DeepSpeed config and you see how dynamic it is with regards to all the different command line arguments and whatnot. What you could do is split the configuration into a JSON file and override certain config values with the ones we set dynamically; but then you make modifications much harder due to having to keep track of what's being overwritten in the config and what isn't. You'd also have to look into two places to grok the whole config.
> We could place a function like `def create_deepspeed_config(batch_size, fp16, [...])` at the top of the file, then people would be able to find the config sooner.

The configuration stuff is highly subjective and we  don't need to get into a Python dicts vs. JSON argument because I am in fact a proponent of both and in general favor Python by default because it's highly legible still. 

The main reason I want this is because I have to keep adding flags to our CLI arguments when people could just pass in the thing that the DeepSpeed documentation clearly wants you to use and we could provide 4-5 (also highly legible) JSON example files. Do you have a more objective/less preferential reason for this? I really don't like the idea of writing yet another wrapper function we'll have to maintain as their config API changes. This feels me to like rewriting DeepSpeed code.

Anyway I'm kinda unconvinced by this argument that we can't use both and at the very least my version is documented well in the DeepSpeed documentation and our version... sends you to the page for the JSON configuration API straight in the README.md and expects you to figure that out yourself.

**Comment by afiaka87** [comment]
> Just one concern. The current style (of train dalle .py) is low abstraction. The benefit of that is it's easy for anyone to read and understand the code. The drawback as you noticed is it doesn't scale to many features and lines of code.
> I think it may make sense to add some abstraction with a training class but just make sure not to add too much abstraction and lose the easy to understand property.
> That's a trap of this kind of refactoring, let's not fall into it :)

Yeah this is something I've had to get used to as a software engineer in research land and I totally understand the reasoning here - the code is meant to be used as a tool for research and as such having most things in one file is actually better. I think I understand how to strike that balance now and actually think some of the things I've done in the past (like moving the data loader into the `dalle_pytorch` folder) should actually be reconsidered because, indeed; it obscures your ability to easily add augmentation and to tinker with parameters. 

Perhaps this will be a better place to start - what of my post does anyone _agree_ with? Criticism has been fairly constructive so far but just a bit vague which can serve to demotivate and sow doubt.

**Comment by afiaka87** [comment]
With regard to the loop @janEbert - even this is in disagreement? LIke - I just want to put it into a function above the for loop at the bottom - everything will all still be in one file but will have less nesting and allow us to use early returns which is something we can't do currently.

Furthermore this is becoming standard practice in many frameworks including W&B and pytorch-lightning. It is far cleaner in my opinion and you can check lucidrains other codebases to see that he's implemented the training loop in this way before.

**Comment by rom1504** [comment]
Yeah to be clear I was not saying not to do it (the training class), just being careful about it.
I think the next step is trying things out :)
It'll be easier this to discuss with code

**Comment by janEbert** [comment]
@afiaka87 with regard to the loop comment, I don't disagree with putting the loop (or I'm guessing training step) into its own function. Just like I'd favor having a `main` with corresponding `if __name__ == '__main__'` guard. I was just referring to not including too many abstracting functions in it. :)

Just to be clear, I agree with or am neutral towards what I didn't write about!

**Comment by janEbert** [comment]
Regarding the DeepSpeed configuration, please make me aware of subjective points; from my point of view, I can't see where I listed a single subjective opinion. It's obviously harder to understand and modify a non-centralized, or split, configuration. Using the common API to modify things like batch size is also objectively superior; you can reuse the same arguments for DeepSpeed that you used for non-distributed or even Horovod training as well as not having a redundant argument when using DeepSpeed (leading to even more confusion).

I understand that the DeepSpeed examples all use a JSON file; however, you have to remember that these code bases are heavily intertwined with DeepSpeed, where they do not even support _not_ using DeepSpeed. Keeping both the compatibility with the common API and the flexibility of DeepSpeed being optional simply requires Python modifications of the dictionary. If we were to merge with JSON, this leads to the issues I listed like making the configuration harder to understand. At _no_ point is it ever required to use a JSON file for DeepSpeed ([not even for inference unlike the tutorial states; see the `checkpoint` argument](https://deepspeed.readthedocs.io/en/latest/inference-init.html#deepspeed.init_inference)). [We even warn users about supplying a JSON config.](https://github.com/lucidrains/DALLE-pytorch/blob/d6107ccc24f2fbbc72e1fabbd97f01e6b143606d/dalle_pytorch/distributed_backends/deepspeed_backend.py#L100-L103)

I also do not see the need to have a command line argument for every single DeepSpeed option; in this repo's README, it's clearly stated that you are supposed to modify the Python `deepspeed_config` dictionary using the DeepSpeed JSON config documentation as help. DeepSpeed is a large library, we could provide command line arguments for every single option in there, but in the end, they lose their meaning for every other library that is supported which goes against the whole idea of having an distribution-framework-agnostic codebase.

**Comment by afiaka87** [comment]
Anyway I don't have time to work on this now. If anyone else would like to pick up the task feel free.

**Comment by afiaka87** [comment]
I'm gonna close this because I actually just don't think it's feasible given how distracted lucidrains is currently and the level of timezone changing/PR debating/miscommunicating/potentially duplicating honestly sounds worse than an actual job which is very much not why I do this in my spare time. Not meant as a slight to anyone - just being real.
