### ISSUE TITLE
Show the Dall-E Pytorch Discord group more prominently.

### ISSUE THREAD

**Issue by johnpaulbin** [lucidrains/DALLE-pytorch#312]
Hi there, would it be possible to add the Dall-E Pytorch discord group to appear in the read me more prominently?

We need this for a couple of reasons:
 - If newcomers come to this Repo and have no idea where to start, we can lead them in the right direction.
 - We need a lot of people that are willing to help with our endeavors. This includes creating the massive Dall-E Dataset. (http://crawlingathome.duckdns.org)
 - I personally think that making a discord group will allow people to become more interested with Dall-E, due to the fact all conversation is done real time; very fast support with Dall-E related questions, and is more of a community.

There are many more reasons and use cases, but please do consider allowing this discord group be featured more prominently inside the readme.
(https://discord.gg/dall-e)

**Comment by johnpaulbin** [comment]
We've also managed to obtain a vanity URL thanks to a community member.

**Comment by robvanvolt** [comment]
Do you have an idea how to do it? On the one hand, it is nice to have people who at least read the first 2 sections of the readme in the discord channel, to avoid easy to answer questions - on the other hand, we could maybe create a small section about the discord channel and to state the goals (free open access to heavy models, independent liberalisation of AI).. :)

**Comment by afiaka87** [comment]
@johnpaulbin @robvanvolt 

addressed here - hope top of the README is good enough ;)

https://github.com/lucidrains/DALLE-pytorch/issues/312

**Comment by robvanvolt** [comment]
> @johnpaulbin @robvanvolt
> 
> addressed here - hope top of the README is good enough ;)
> 
> #320

I like!

**Comment by johnpaulbin** [comment]
Awesome! Marged, thanks @afiaka87
