### ISSUE TITLE
Out of memory when using train_vae.py

### ISSUE THREAD

**Issue by soloist97** [lucidrains/DALLE-pytorch#331]
Thanks for your great work. 

I tried to train a discrete vae from scratch with a single  2080Ti and 20GB memory in total. I found that the memory consumption kept growing until the process was killed by the system.  Do you have any idea about how this happen and what I can do about it?

Here are more information:

- Ubuntu 18.04  + python3.7  + pip install dalle-pytorch
- The dataset I used is flickr30k + Using the comand `python train_vae.py --image_size 256`
- I further commented out all the codes related to `wandb` , but the training process was still killed by the system

Thanks in advance.

**Comment by kswain98** [comment]
> Thanks for your great work.
> 
> I tried to train a discrete vae from scratch with a single 2080Ti and 20GB memory in total. I found that the memory consumption kept growing until the process was killed by the system. Do you have any idea about how this happen and what I can do about it?
> 
> Here are more information:
> 
> * Ubuntu 18.04  + python3.7  + pip install dalle-pytorch
> * The dataset I used is flickr30k + Using the comand `python train_vae.py --image_size 256`
> * I further commented out all the codes related to `wandb` , but the training process was still killed by the system
> 
> Thanks in advance.

Hi! As far as I am aware, the 2080Ti only has 11 GB of VRAM.  Try cutting the batch size in half and watch for peaks of VRAM usage since it can vary depending on the process. I highly recommend using PyTorch AMP or FP16 to reduce memory usage.

**Comment by soloist97** [comment]
I solved it by disabling all code related to  distributed training, I guess it is not feasible when you have only one gpu but you use distributed training method.
