### ISSUE TITLE
DO YOU KNOW YOUR DATASETS?

### ISSUE THREAD

**Issue by asigalov61** [lucidrains/DALLE-pytorch#334]
Hey @lucidrains and contribs

What is the detected plagiarism rate in your reproduction implementation? Did you even bother to familiarize yourself with your datasets so that you can properly improve and compile them!

Therefore, think the reason why you guys not getting good results with the replication of DALLE is that you completely forgetting that the DATASET IS EVERYTHING! 

THIS IS HOW THEY DID IT! Improving the transformer implementation alone is not going to produce similarly impressive results to that of OpenAI.

P.S. @lucidrains specifically.... No need to be a pompous dick, bro! I understand that you are a dog lover and therefore you are subservient to your master (whoever that may be)... But seriously, stop power tripping!!! You are not that important or not irreplaceable!

Cheers!

Alex

**Comment by lucidrains** [comment]
something is wrong with him, blocked

**Comment by lucidrains** [comment]
you don't sound ok. hope you feel better
