### ISSUE TITLE
missing clip?

### ISSUE THREAD

**Issue by skywo1f** [lucidrains/DALLE-pytorch#34]
I was able to train the vae, but I am now stuck on the dalle training step. It is telling me:
loading state dict from vae.pt
preloading txt files...
processing 72496/72496
done preloading txt onehots
Train Epoch: 1 [0/72496 (0%)]	Loss: 0.569296
Traceback (most recent call last):
  File "dalle.py", line 615, in <module>
    main()
  File "dalle.py", line 608, in main
    train_dalle(vae, args)
  File "dalle.py", line 331, in train_dalle
    if clip is not None:
UnboundLocalError: local variable 'clip' referenced before assignment

**Comment by lucidrains** [comment]
@skywo1f Hi! Could you provide the full script? I never use the line `if clip is not None` in my code

**Comment by lucidrains** [comment]
I'll be providing the full training scripts this weekend :)

**Comment by Thierryonre** [comment]
Is anybody going to be releasing any decent pretrained models?
I'm assuming they aren't going to be 12B parameter models like OpenAI's.

**Comment by lucidrains** [comment]
I think I figured out the axial and convolutional sparse attention they are doing. I'll be adding thise two custom sparse attention classes to the repo tomorrow

**Comment by skywo1f** [comment]
thats my bad. I posted in the wrong git haha
