### ISSUE TITLE
How to cite your work. 

### ISSUE THREAD

**Issue by WocMaker** [lucidrains/DALLE-pytorch#344]
Dear Wang
I used the code in my master project.
I think it's necessary to mark that  the reprodution of DALL-E model is your work.
But I'm wondering how can I cite your DALL-E work, could you or anyone please give me some suggestion on this problem?
Thanks a lot!
Zhilin

**Comment by lucidrains** [comment]
@WocMaker hey, don't worry about citing! i'm not an academic

the project is MIT, which means you are free to use it for anything you wish

**Comment by lucidrains** [comment]
@WocMaker just spread the word that attention is all you need :)

**Comment by WocMaker** [comment]
> @WocMaker hey, don't worry about citing! i'm not an academic
> 
> the project is MIT, which means you are free to use it for anything you wish

Thanks, lucidrains！ I added a reference of your respo with your name Phil Wang. Hope it's okay.
