### ISSUE TITLE
Missing keys while testing pre-trained models

### ISSUE THREAD

**Issue by Radeeswar** [lucidrains/DALLE-pytorch#352]
Hi, i am trying to generate image for some tests using "https://github.com/robvanvolt/DALLE-models"
 models, But its failing to load model with error as:
RuntimeError: Error(s) in loading state_dict for DALLE:
	Missing key(s) in state_dict: "transformer.pos_emb", "transformer.layers.blocks.0.f.net.fn.fn.fn.to_qkv.weight", "transformer.layers.blocks.0.f.net.fn.fn.fn.to_out.0.weight", "transformer.layers.blocks.0.f.net.fn.fn.fn.to_out.0.bias", "transformer.layers.blocks.0.g.net.fn.fn.fn.net.0.weight", "transformer.layers.blocks.0.g.net.fn.fn.fn.net.0.bias", "transformer.layers.blocks.0.g.net.fn.fn.fn.net.3.weight", "transformer.layers.blocks.0.g.net.fn.fn.fn.net.3.bias", "transformer.layers.blocks.1.f.net.fn.fn.fn.to_qkv.weight", "transformer.layers.blocks.1.f.net.fn.fn.fn.to_out.0.weight", "transformer.layers.blocks.1.f.net.fn.fn.fn.to_out.0.bias", "transformer.layers.blocks.1.g.net.fn.fn.fn.net.0.weight", "transformer.layers.blocks.1.g.net.fn.fn.fn.net.0.bias", "transformer.layers.blocks.1.g.net.fn.fn.fn.net.3.weight", "transformer.layers.blocks.1.g.net.fn.fn.fn.net.3.bias", "transformer.layers.blocks.2.f.net.fn.fn.fn.to_qkv.weight", "transformer.layers.blocks.2.f.net.fn.fn.fn.to_out.0.weight", "transformer.layers.blocks.2.f.net.fn.fn.fn.to_out.0.bias", "transformer.layers.blocks.2.g.net.fn.fn.fn.net.0.weight", "transformer.layers.blocks.2.g.net.fn.fn.fn.net.0.bias", "transformer.layers.blocks.2.g.net.fn.fn.fn.net.3.weight", "transformer.layers.blocks.2.g.net.fn.fn.fn.net.3.bias", "transformer.layers.blocks.3.f.net.fn.fn.fn.to_qkv.weight", "transformer.layers.blocks.3.f.net.fn.fn.fn.to_out.0.weight", "transformer.layers.blocks.3.f.net.fn.fn.fn.to_out.0.bias", "transformer.layers...
	Unexpected key(s) in state_dict: "text_pos_emb.weight", "image_pos_emb.weights_0", "image_pos_emb.weights_1", "transformer.layers.blocks.0.f.net.fn.fn.to_qkv.weight", "transformer.layers.blocks.0.f.net.fn.fn.to_out.0.weight", "transformer.layers.blocks.0.f.net.fn.fn.to_out.0.bias", "transformer.layers.blocks.0.f.net.fn.fn.attn_fn.master_layout", "transformer.layers.blocks.0.g.net.fn.fn.net.0.weight", "transformer.layers.blocks.0.g.net.fn.fn.net.0.bias", "transformer.layers.blocks.0.g.net.fn.fn.net.3.weight", "transformer.layers.blocks.0.g.net.fn.fn.net.3.bias", "transformer.layers.blocks.1.f.net.fn.fn.to_qkv.weight", "transformer.layers.blocks.1.f.net.fn.fn.to_out.0.weight", "transformer.layers.blocks.1.f.net.fn.fn.to_out.0.bias", "transformer.layers.blocks.1.f.net.fn.fn.attn_fn.master_layout", "transformer.layers.blocks.1.g.net.fn.fn.net.0.weight", "transformer.layers.blocks.1.g.net.fn.fn.net.0.bias", "transformer.layers.blocks.1.g.net.fn.fn.net.3.weight", "transformer.layers.blocks.1.g.net.fn.fn.net.3.bias", "transformer.layers.blocks.2.f.net.fn.fn.to_qkv.weight", "transformer.layers.blocks.2.f.net.fn.fn.to_out.0.weight", "transformer.layers.blocks.2.f.net.fn.fn.to_out.0.bias", "transformer.layers.blocks.2.f.net.fn.fn.attn_fn.master_layout", "transformer.layers.blocks.2.g.net.fn.fn.net.0.weight", "transformer.layers.blocks.2.g.net.fn.fn.net.0.bias", "transformer.layers.blocks.2.g.net.fn.fn.net.3.weight", "transformer.layers.blocks.2.g.net.fn.fn.net.3.bias", "transformer...
 
Please provide any suggestions. Thanks!

**Comment by rom1504** [comment]
This is due to https://github.com/lucidrains/DALLE-pytorch/commit/63effa53fceb1c66c1f3b3f98d6435c2d89e74b9 ; all previous models are now incompatible with the current code
You may still be able to load old models by putting shift_tokens and rotary_emb to False in the loading/generation code

**Comment by Radeeswar** [comment]
> This is due to [63effa5](https://github.com/lucidrains/DALLE-pytorch/commit/63effa53fceb1c66c1f3b3f98d6435c2d89e74b9) ; all previous models are now incompatible with the current code
> You may still be able to load old models by putting shift_tokens and rotary_emb to False in the loading/generation code

Many thanks @rom1504, still not able to load getting unexpected keys error as:
Unexpected key(s) in state_dict: "transformer.layers.blocks.0.f.net.fn.fn.attn_fn.master_layout", "transformer.layers.blocks.1.f.net.fn.fn.attn_fn.master_layout", "transformer.layers.blocks.2.f.net.fn.fn.attn_fn.master_layout", "transformer.layers.blocks.3.f.net.fn.fn.attn_fn.master_layout", "transformer.layers.blocks.4.f.net.fn.fn.attn_fn.master_layout", "transformer.layers.blocks.5.f.net.fn.fn.attn_fn.master_layout", "transformer.layers.blocks.6.f.net.fn.fn.attn_fn.master_layout", "transformer.layers.blocks.7.f.net.fn.fn.attn_fn.master_layout", "transformer.layers.blocks.8.f.net.fn.fn.attn_fn.master_layout", "transformer.layers.blocks.9.f.net.fn.fn.attn_fn.master_layout", "transformer.layers.blocks.10.f.net.fn.fn.attn_fn.master_layout", "transformer.layers.blocks.11.f.net.fn.fn.attn_fn.master_layout", "transformer.layers.blocks.12.f.net.fn.fn.attn_fn.master_layout", "transformer.layers.blocks.13.f.net.fn.fn.attn_fn.master_layout", "transformer.layers.blocks.14.f.net.fn.fn.attn_fn.master_layout", "transformer.layers.blocks.15.f.net.fn.fn.attn_fn.master_layout".

**Comment by rom1504** [comment]
> after putting shift_tokens and rotary_emb to False
where did you do that exactly?

**Comment by Radeeswar** [comment]
> > after putting shift_tokens and rotary_emb to False
> 
> where did you do that exactly?

In the DALLE function, please check below,

from dalle_pytorch import OpenAIDiscreteVAE, DALLE
dalle = DALLE(dim = 512,    vae = vae, num_text_tokens = 10000, 
    text_seq_len = 256,  depth = 12,  heads = 16,  dim_head = 64,
   shift_tokens = False,
   rotary_emb =False
   )

**Comment by rom1504** [comment]
in what file ?

**Comment by Radeeswar** [comment]
> in what file ?

In generate.py file below is the link.
https://github.com/lucidrains/DALLE-pytorch/blob/main/generate.py

**Comment by Radeeswar** [comment]
Hi @rom1504,I did some mistake, It worked. Thank you
