### ISSUE TITLE
Running in Colab: AttributeError: module 'keras.backend' has no attribute 'is_tensor'

### ISSUE THREAD

**Issue by guillermoAlv** [lucidrains/DALLE-pytorch#356]
Hi, first of all thanks for the amazing job and repo!!!
Triying to run the colab notebook I'm getting the following error on the last cell and no image is generated.

AttributeError: module 'keras.backend' has no attribute 'is_tensor'

Thanks in advanced for your help

**Comment by scy6500** [comment]
Hi, I also had the same error, but it was resolved by changing the version. 
What version are you using? I'm using 0.14.3 version and it worked.

**Comment by guillermoAlv** [comment]
Thanks a lot for your answer. Do you mean PyTorch version?

**Comment by scy6500** [comment]
nop! it's dalle-pytorch version.

I deployed dalle-pytorch on a site called Ainize. Check it out!
Demo : https://main-dalle-client-scy6500.endpoint.ainize.ai/
API : https://ainize.ai/scy6500/DALLE-server?branch=main

**Comment by lucidrains** [comment]
@guillermoAlv Hi! Do you want to upgrade to v1.0.7 and see if that fixes this error?
