### ISSUE TITLE
how to do with video input?

### ISSUE THREAD

**Issue by Eddie-Hwang** [lucidrains/DALLE-pytorch#37]
if i want to generate video with vq vae, how to do with your code?

**Comment by lucidrains** [comment]
@Eddie-Hwang hey! you'll want to follow the instructions in this paper https://openreview.net/forum?id=3InxcRQsYLf it'll be an entirely different architecture (though similar)

**Comment by lucidrains** [comment]
@Eddie-Hwang i ran into another user of my repos who is combining https://github.com/lucidrains/vector-quantize-pytorch with https://github.com/lucidrains/compressive-transformer-pytorch
