### ISSUE TITLE
--taming should ignore vae_params

### ISSUE THREAD

**Issue by TomorrowToday** [lucidrains/DALLE-pytorch#370]
`python generate.py --taming` should ignore vae_params saved into the checkpoint so older dall-e models (or models trained elsewhere) with vae_params in their checkpoints can still be loaded easily.

I think it'd be just changing:
```
if vae_params is not None:
    vae = DiscreteVAE(**vae_params)
elif not args.taming:
    vae = OpenAIDiscreteVAE()
else:
    vae = VQGanVAE(args.vqgan_model_path, args.vqgan_config_path)
```

To:
```
if args.taming:
    vae = VQGanVAE(args.vqgan_model_path, args.vqgan_config_path)
elif vae_params is not None:
    vae = DiscreteVAE(**vae_params)
else:
    vae = OpenAIDiscreteVAE()
```

**Comment by lucidrains** [comment]
@TomorrowToday ok, i made the change in https://github.com/lucidrains/DALLE-pytorch/commit/3df569d3921ef46de888708e0cb51bdd67e85a4e !
