### ISSUE TITLE
Hierarchical (Hourglass) Transformer

### ISSUE THREAD

**Issue by nsankar** [lucidrains/DALLE-pytorch#382]
Any plans to enhance or create a improved version of a DALLE equivalent using the Hourglass attention transformers ? Would be great to know . 

References:
https://arxiv.org/pdf/2110.13711.pdf
https://github.com/google/trax/blob/master/trax/models/research/hourglass.py

As cited in the paper, While DALLE is great, its quite costly and difficult to use in production grade scenarios.

**Comment by lucidrains** [comment]
@nsankar oh hey! i'm actually running some experiments on hourglass architecture today. it is still mostly an unproven architecture

**Comment by nsankar** [comment]
@lucidrains cool! would be great to know about it when you complete your experiments and findings including a package if any. Thanks.

**Comment by lucidrains** [comment]
yea sure, i'll put it here https://github.com/lucidrains/hourglass-transformer-pytorch
