### ISSUE TITLE
How to improve image fidelity?

### ISSUE THREAD

**Issue by soon-yau** [lucidrains/DALLE-pytorch#390]
![brown](https://user-images.githubusercontent.com/19167278/143328331-6fb1f1a7-1094-478d-a0c5-615192a9b3e9.png)
(Left:generated. Right: from dataset)
I have trained on mannequin dataset and the results look quite good. However, the generated images are a bit blurry and fine details are lost. Therefore, I wonder what changes do I need to do make them look crispier.

I currently use VQGAN pretrained on imagenet. I have also tried to train a VAE from scratch (using default train_vae.py) but it is blurry. I tried increasing the number of layers, number of tokens etc but didn't see improvement and made it a bit more unstable. Any advise on what VAE parameters to change?

**Comment by rom1504** [comment]
You could try to use vqgan 16k or even the f=8 ( see the details on their
page)

**Comment by soon-yau** [comment]
Managed to train a mannequin-only model that produces quality matching OpenAI
![mannequin_female_2](https://user-images.githubusercontent.com/19167278/143679121-118c8d70-9044-40c5-b100-60077eb54d94.png)

**Comment by huang-xx** [comment]
@soon-yau  Hi,  I am trying to train a model using vqgan_gumbel_f8_8192 as you do,  but I get terrible results. What model parameters did you use to get this result, especially the number of layers and dimensions? Also, could you please provide a link to the "mannequin dataset"?  Thanks
