### ISSUE TITLE
padding in PreShiftToken

### ISSUE THREAD

**Issue by sklin93** [lucidrains/DALLE-pytorch#405]
https://github.com/lucidrains/DALLE-pytorch/blob/459c46a435405e2ece49313fc0d72d428f4de22a/dalle_pytorch/transformer.py#L104

It seems here assumes n > text_len, and is using padding = img_seq_len - (n - text_len) = seq_len - n + 1, which will give rise to shape errors when using dalle model's generate_text.
It should be `padding = img_seq_len - max(n - text_len, 0)`?

**Comment by lucidrains** [comment]
oh shoot, someone else actually contributed the `generate_text` functionality, so i didn't account for that

do you want to try a pull request? :)

**Comment by sklin93** [comment]
> 

Sure! I created a pull request https://github.com/lucidrains/DALLE-pytorch/pull/406
