### ISSUE TITLE
faster inference

### ISSUE THREAD

**Issue by rom1504** [lucidrains/DALLE-pytorch#407]
using caching @borzunov implemented 10x faster generation at https://github.com/learning-at-home/dalle-pytorch/pull/3/files

I think this could be useful

**Comment by lucidrains** [comment]
oh nice! yeah, I can get this done for both dalle and nuwa in one go when I get a free stretch of time

**Comment by borzunov** [comment]
I think the code is ready, see #409. This branch is based on the branch from #408.
