### ISSUE TITLE
rotary embedding values

### ISSUE THREAD

**Issue by sklin93** [lucidrains/DALLE-pytorch#413]
The reason for using value -10 [here](https://github.com/lucidrains/DALLE-pytorch/blob/289fddbef7e5a9b4c6f3f223a7505c34afe4ac67/dalle_pytorch/transformer.py#L321) is " image axial positions have range [-1, 1]", but in fact, in the `RotaryEmbedding` class, for
`img_axial_pos_emb = RotaryEmbedding(dim = rot_dim, freqs_for = 'pixel')`
`img_freqs_axial = img_axial_pos_emb(torch.linspace(-1, 1, steps = image_fmap_size))`

freqs (has its default value [here](https://github.com/lucidrains/rotary-embedding-torch/blob/a81118140274c35a5f40ac3c7a4fb762d6022fe7/rotary_embedding_torch/rotary_embedding_torch.py#L78)) and t (ranges in [-1, 1]) will [einsum](https://github.com/lucidrains/rotary-embedding-torch/blob/a81118140274c35a5f40ac3c7a4fb762d6022fe7/rotary_embedding_torch/rotary_embedding_torch.py#L100), and the results are not in range [-1, 1]. (e.g. if using head_dim=64, aka rot_dim=21, then the img_freqs with range from -15.7 to 15.7) and I think this makes the choice of -10 not suitable?

**Comment by lucidrains** [comment]
so the `-10` is just to make sure the relative distance of each image token to each text token is sufficiently larger [9, 11] than the distance between the image feature tokens [-2, 2]

**Comment by sklin93** [comment]
thank you!
