### ISSUE TITLE
Installation Problems.

### ISSUE THREAD

**Issue by HanshustlerHHHH** [lucidrains/DALLE-pytorch#452]
Can someone explain to me why i get this error the whole time? 

i tried "pip install dalle-pytorch" 20 times now always this error :( 

I installed "[Visual Studio 2022](https://visualstudio.microsoft.com/de/vs)"

i m a noob XD 

_________________________

**DEPRECATION: youtokentome is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for youtokentome ... error
  error: subprocess-exited-with-error

  × Running setup.py install for youtokentome did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      running install
      C:\Users\Bastl\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\youtokentome
      copying youtokentome\youtokentome.py -> build\lib.win-amd64-cpython-310\youtokentome
      copying youtokentome\yttm_cli.py -> build\lib.win-amd64-cpython-310\youtokentome
      copying youtokentome\__init__.py -> build\lib.win-amd64-cpython-310\youtokentome
      running build_ext
      building '_youtokentome_cython' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> youtokentome

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.**

**Comment by thygate** [comment]
>I installed "[Visual Studio 2022](https://visualstudio.microsoft.com/de/vs)"

You need the C++ build tools, not just the editor (visual studio).

The link to it is even in the stack trace :|

>error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
