### ISSUE TITLE
hparams missing

### ISSUE THREAD

**Issue by robvanvolt** [lucidrains/DALLE-pytorch#48]
```
  File "train_dalle.py", line 43, in <module>
    vae_params, weights = loaded_obj['hparams'], loaded_obj['weights']
KeyError: 'hparams'
```
After training the vae i wanted to train dall_e next, but after successfully loading the VAE the hparams is not defined, see terminal output above. Is this a problem of the trained VAE or is the bug in train_dalle.py?

Thanks in advance! Great project! :-)

**Comment by robvanvolt** [comment]
You need to update the train_vae.py and create a new model with stored hyperparameters! Then you can use the train_dalle.py script!

**Comment by lucidrains** [comment]
@robvanvolt hey! it should be fixed now! is it working for you?

**Comment by robvanvolt** [comment]
Yeah, the issue got fixed right after i posted my question! I trained a new vae-model and then the train_dalle.py worked right away! Thank you!

**Comment by lucidrains** [comment]
Ok great!
