### ISSUE TITLE
Continue training on Dalle model

### ISSUE THREAD

**Issue by robvanvolt** [lucidrains/DALLE-pytorch#51]
I haven't found a function for continuing training on the Dalle model - is it analogue to loading VAE in the train_dalle.py?

```
vae_path = Path(args.vae_path)
assert vae_path.exists(), 'VAE model file does not exist'

loaded_obj = torch.load(str(vae_path))

vae_params, weights = loaded_obj['hparams'], loaded_obj['weights']

vae = DiscreteVAE(**vae_params)
vae.load_state_dict(weights)
```

**Comment by lucidrains** [comment]
@robvanvolt Hello! I've added that feature in the latest commit https://github.com/lucidrains/DALLE-pytorch/commit/72dfd7b53e8bb3b7804642157ecf333e76902421 Let me know if it works or not!

**Comment by robvanvolt** [comment]
Great - works as expected!
