### ISSUE TITLE
Axial Positional Embedding defined wrong?

### ISSUE THREAD

**Issue by adrian-spataru** [lucidrains/DALLE-pytorch#52]
I think Axial Positional Embedding is initialized wrong.

`self.image_pos_emb = AxialPositionalEmbedding(dim, axial_shape = (image_size, image_size))`
where image_size is the image_size we pass to the VAE. Default: 256, therefore the max_length is 256*256.
It wouldn't make a big difference, but this should be set to the discrete latent space size of the vqvae. Ex. 16 (16x16= 256)

**Comment by lucidrains** [comment]
@adrian-spataru oh my god, yess 🙏  thanks for catching this

**Comment by lucidrains** [comment]
@adrian-spataru fixed in the latest https://github.com/lucidrains/DALLE-pytorch/releases/tag/0.1.26
