### ISSUE TITLE
Arbitrary vocab size in text embedding might lead to undesired incomes.

### ISSUE THREAD

**Issue by adrian-spataru** [lucidrains/DALLE-pytorch#56]
The BPE Tokenizer which you provide ( the one from CLIP) has a vocab size around 40k.
When training DALL-E on your own dataset, the default parameter of the text embedding is 10k.
For most cases, this won't lead to any problems, however depending on the words you might have tokens which have a id over 10k. One example is "mental health", which has a token Id around 20k. 
I went through the code & haven't seen anything deal with this problem. If thats the case, here are my suggestions:
1) Just set the default value of the text embedding size to the vocab size of the tokenizer. Or at least warn the user in the README.md
2) Before training the model, go through the data loader and get the largest Id from the dataset and then set the model to that size. 
3) A more elegant solution would be to build a set with all the ids in the dataset and define the size of the embedding accordingly. Disadvantage of this solution is that we need a extra map to translate between the ids, since the ids won't necessary match with the embedding 

I could implement solution 2 or 3, if needed. But I think just making the user aware of the problem, should be enough.

**Comment by lucidrains** [comment]
@adrian-spataru I set that here! https://github.com/lucidrains/DALLE-pytorch/blob/main/train_dalle.py#L103 if you were to train with your own BPEs you will just have to set the right value yourself

**Comment by adrian-spataru** [comment]
@lucidrains  Totally missed that! 😅 Nevermind then.

**Comment by lucidrains** [comment]
@adrian-spataru thanks for reviewing the code :)
