### ISSUE TITLE
out-of-place masked filled

### ISSUE THREAD

**Issue by dar-tau** [lucidrains/DALLE-pytorch#62]
1) First apperance:
https://github.com/lucidrains/DALLE-pytorch/blob/0d43aa8080d622d4350819452764fc83153b3872/dalle_pytorch/attention.py#L120

2) Second appearance:
https://github.com/lucidrains/DALLE-pytorch/blob/0d43aa8080d622d4350819452764fc83153b3872/dalle_pytorch/attention.py#L229

**Comment by lucidrains** [comment]
@dar-tau :pray: :pray: https://github.com/lucidrains/DALLE-pytorch/commit/02f055486438290733d20d200b54cd9282d2c41b
