### ISSUE TITLE
Please, explain me! Begging  

### ISSUE THREAD

**Issue by gqbay** [lucidrains/DALLE-pytorch#67]
Using Conda

$ pip install dalle-pytorch

Everything seems fine. 

What is my next step? Can I use some ready to use database? How do I use this AI? Please, someone, help me!

(base) d:\ai\dalle\DALLE>pip install dalle-pytorch
Requirement already satisfied: dalle-pytorch in c:\users\administrator\miniconda3\lib\site-packages (0.0.48)
Requirement already satisfied: einops>=0.3 in c:\users\administrator\miniconda3\lib\site-packages (from dalle-pytorch) (0.3.0)
Requirement already satisfied: axial-positional-embedding in c:\users\administrator\miniconda3\lib\site-packages (from dalle-pytorch) (0.2.1)
Requirement already satisfied: torch>=1.6 in c:\users\administrator\miniconda3\lib\site-packages (from dalle-pytorch) (1.7.1)
Requirement already satisfied: typing-extensions in c:\users\administrator\miniconda3\lib\site-packages (from torch>=1.6->dalle-pytorch) (3.7.4.3)
Requirement already satisfied: numpy in c:\users\administrator\miniconda3\lib\site-packages (from torch>=1.6->dalle-pytorch) (1.20.0)

(base) d:\ai\dalle\DALLE>pip install git+https://github.com/openai/DALL-E.git
Collecting git+https://github.com/openai/DALL-E.git
  Cloning https://github.com/openai/DALL-E.git to c:\users\administrator\appdata\local\temp\pip-req-build-wwzg5x63
  ERROR: Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/openai/DALL-E.git 'C:\Users\Administrator\AppData\Local\Temp\pip-req-build-wwzg5x63'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

(base) d:\ai\dalle\DALLE>pip install https://github.com/openai/DALL-E.git
Collecting https://github.com/openai/DALL-E.git
  Downloading https://github.com/openai/DALL-E.git
     / 138 kB 472 kB/s
  ERROR: Cannot unpack file C:\Users\Administrator\AppData\Local\Temp\pip-unpack-o2tnnu_w\DALL-E.git (downloaded from C:\Users\Administrator\AppData\Local\Temp\pip-req-build-_1pfco24, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of C:\Users\Administrator\AppData\Local\Temp\pip-req-build-_1pfco24

**Comment by robvanvolt** [comment]
There is no ready-to-use  database - you have to download a dataset yourself (e.g. coco2018), to run the script. If your git commands do not work, just download this repository, open with the editor you use (e.g. Visual studio code) and run the script as mentioned in the docs.

`python train_vae.py --image_folder /path/to/your/images`

for training the VAE and 

`python train_dalle.py --vae_path ./vae.pt --image_text_folder /path/to/data`

to train Dall-e with the VAE trained before. Alternatively, you can skip training the VAE and just use the Open-AI pretrained VAE, as mentioned by lucidrains in the docs, by just omitting the vae path:

`python train_dalle.py --image_text_folder /path/to/coco/dataset`

I recommend reading the github docs in detail and read some general information on visual auto encoders (VAE) and neural networks.

**Comment by gqbay** [comment]
Thank you! Will try 🙏

**Comment by afiaka87** [comment]
@gqbay 
Can you please close this issue?
