### ISSUE TITLE
Wrong image transform will cause OpenAI VAE return all 0 for image indices.

### ISSUE THREAD

**Issue by hopeisme** [lucidrains/DALLE-pytorch#71]
https://github.com/lucidrains/DALLE-pytorch/blob/4fa108271aeb1972fcb118390ec15b656f2c328a/train_dalle.py#L151-L152

I found removing the two lines would solve the problem, according to the operation in the official DALLE image reconstruction code.

**Comment by lucidrains** [comment]
@hopeisme Hi Xi! Indeed I went back to the original notebook and I cannot find that normalization. I don't know why I put that there, but thank you for catching this error!
