### ISSUE TITLE
Is it necessary to predict the text token indices for the embeddings in transformer?

### ISSUE THREAD

**Issue by liuqk3** [lucidrains/DALLE-pytorch#76]
Hi, @lucidrains,
Thanks for your great works! The embeddings in the transformer is first fed into several attention layers, then a classification head is performed: each embedding is classified into one of (num_text_tokens+num_image_tokens) classes rather than num_image_tokens. However, the text condition is given at once without autoregression, and what we need to know is which the image token the embedding belonging to. So is it necessary for embeddings to be classified into (num_text_tokens+num_image_tokens) classes rather than num_image_tokens?

**Comment by lucidrains** [comment]
@liuqk3 I think so, from what I understand, the text part still undergoes autoregressive modeling, like a regular GPT

**Comment by liuqk3** [comment]
@lucidrains Thanks for your reply. Here is another question. In CLIP, the number of text tokens is 49408. The BPE file used in this reop. is the same with that in CLIP, but in your instructions about the usage in README.md, the number of text tokens in set to 10000? Is that OK?
