### ISSUE TITLE
Is there a bug in SparseConvCausalAttention and SparseAxialCausalAttention ?

### ISSUE THREAD

**Issue by liuqk3** [lucidrains/DALLE-pytorch#78]
Hi @lucidrains, In the forward function of classes SparseConvCausalAttention and SparseAxialCausalAttention, the input embeddings `x` wil first be mapped into `qkv`, then one of them will be divided into text and image like:
 `((q_text, q_img), (k_text, k_img), (v_text, v_img)) = map(lambda t: (t[:, img_seq_len:], t[:, -img_seq_len:]), (q, k, v))`

However, I am wondering that should not  it be: 
 `((q_text, q_img), (k_text, k_img), (v_text, v_img)) = map(lambda t: (t[:, :text_len], t[:, -img_seq_len:]), (q, k, v))`
since the text tokens are in the front of input embeddings `x` ?

**Comment by lucidrains** [comment]
@liuqk3 Oh gosh, yes, thank you for catching that :pray:  https://github.com/lucidrains/DALLE-pytorch/commit/3a6afdebcb344ae8d73edf4054f507f2bc6f2b8f
