### ISSUE TITLE
Getting "cannot import name 'VQGanVAE1024' from 'dalle_pytorch'"

### ISSUE THREAD

**Issue by jp-krow** [lucidrains/DALLE-pytorch#79]
After I run 
`!python DALLE-pytorch-0.3.0/train_dalle.py --image_text_folder=./CUB_200_2011`
( im on google collab btw ) 

I get this:
```
Traceback (most recent call last):
  File "DALLE-pytorch-0.3.0/train_dalle.py", line 21, in <module>
    from dalle_pytorch import OpenAIDiscreteVAE, VQGanVAE1024, DiscreteVAE, DALLE
ImportError: cannot import name 'VQGanVAE1024' from 'dalle_pytorch' (/content/DALLE-pytorch-0.3.0/dalle_pytorch/__init__.py)
```

(This is AFTER I ran `!pip install dalle-pytorch`)

Any help?

**Comment by lucidrains** [comment]
@jp-krow whoops! https://github.com/lucidrains/DALLE-pytorch/releases/tag/0.3.1 :sweat:

**Comment by CodeAunt** [comment]
> @jp-krow whoops! https://github.com/lucidrains/DALLE-pytorch/releases/tag/0.3.1 😓

I don't understand. 
I updated the module with pip and checked the package file but find no problem. 
Still can not import this finally.

But on collab, the module is avaliable. I hope I can use this on my server.

**Comment by afiaka87** [comment]
Can you share the stack trace with us?

**Comment by CodeAunt** [comment]
> Can you share the stack trace with us? @CodeAunt

I finally used DiscreateVAE but found VQGanVAE1024 avaliable just now. It's downloading now.
Thanks.
