### ISSUE TITLE
VQGanVAE1024  "vae must be an instance of DiscreteVAE"

### ISSUE THREAD

**Issue by afiaka87** [lucidrains/DALLE-pytorch#87]
@lucidrains I believe the relevant line is here:

https://github.com/lucidrains/DALLE-pytorch/blob/2268864941d8eef2ba73a4488fe05673d447d493/dalle_pytorch/dalle_pytorch.py#L306

I tried adding it in myself, but it needs the taming imports and I'm not familiar with those.

**Comment by afiaka87** [comment]
Here's a branch where I've added it myself:

https://github.com/lucidrains/DALLE-pytorch/pull/88

After remembering to changed the dim parameter to 1024, I'm now getting this message:
`using pretrained VAE for encoding images to tokens
Working with z of shape (1, 256, 16, 16) = 65536 dimensions.
loaded pretrained LPIPS loss from taming/modules/autoencoder/lpips/vgg.pth
VQLPIPSWithDiscriminator running with hinge loss.`

```bash
    loss = dalle(text, images, mask = mask, return_loss = True)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/dalle_pytorch-0.3.1-py3.8.egg/dalle_pytorch/dalle_pytorch.py", line 437, in forward
    image = self.vae.get_codebook_indices(image)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/dalle_pytorch-0.3.1-py3.8.egg/dalle_pytorch/vae.py", line 138, in get_codebook_indices
    _, _, [_, _, indices] = self.model.encode(img)
  File "/opt/conda/lib/python3.8/site-packages/taming_transformers-0.0.1-py3.8.egg/taming/models/vqgan.py", line 52, in encode
    h = self.encoder(x)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/taming_transformers-0.0.1-py3.8.egg/taming/modules/diffusionmodules/model.py", line 413, in forward
    hs = [self.conv_in(x)]
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
```

**Comment by afiaka87** [comment]
actually, that error only shows up if i hardcode 

/opt/conda/conda-bld/pytorch_1614378083779/work/aten/src/ATen/native/cuda/Indexing.cu:662: indexSelectLargeIndex: block: [19,0,0], thread: [63,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
AssertionError: Sequence length (4096) must be less than the maximum sequence length allowed (1024)

**Comment by lucidrains** [comment]
@afiaka87 ack yes, you are correct! just fixed the remaining issue hopefully https://github.com/lucidrains/DALLE-pytorch/commit/187d62ca761a875c31c5834202921f1b676a6243

**Comment by lucidrains** [comment]
@afiaka87 there's the possibility this could train a lot faster, given it is 256 tokens instead of 1024! (it has an extra layer of downsampling)

**Comment by afiaka87** [comment]
@lucidrains have you gotten it working? i was debugging it for awhile but then i realized my actual problem was that my cuda installation on my cloud instance was borked.

**Comment by lucidrains** [comment]
@afiaka87 yup, I just verified it works, at least that I can get the codebook indices and reconstruct them. I also did a quick run in conjunction with DALL-E and it seems to be fine (though obviously haven't trained it yet)

**Comment by lucidrains** [comment]
@afiaka87 Also realized, that if this VAE works well with DALL-E, it opens up the possibility of training 512 by 512 images :)

**Comment by afiaka87** [comment]
i'll be sure to do another hyperparameter sweep on this one if I can get it working.

**Comment by afiaka87** [comment]
@afiaka87 wow, running at 32 depth, 16 heads (*reversible OFF*) and it only needs 11 GiB of VRAM!

**Comment by afiaka87** [comment]
@lucidrains  it's _significantly_ faster as well. Perhaps converging too quickly. need to check. I'll post back here with a live notebook of the session.

**Comment by afiaka87** [comment]
@lucidrains here you go! https://wandb.ai/afiaka87/full_attention/reports/Live-Training-of-the-VQGanVAE1024-with-DALLE-pytorch--Vmlldzo1MzQ3MDE

**Comment by afiaka87** [comment]
seems to have converged too quickly.

**Comment by lucidrains** [comment]
@afiaka87 haha yea, agreed something doesn't look right

**Comment by afiaka87** [comment]
starting over. gonna have a non-live go at this lol. be back with my results in a few hours probably.

**Comment by lucidrains** [comment]
@afiaka87 ok! i'll keep thinking on whether there may be a bug somewhere

**Comment by afiaka87** [comment]
@lucidrains just for your sanity, i'm already achieving significantly better results just switching back to 3e-4 for my loss. Probably should have done that in the first place. Found 5e-4 worked well for OpenAI's vae in another post, but clearly that's not the case for this vae. Anyway, my dataset has corrupted pngs in it so i'm dealing with that right now, but I just had a much more stable training session:
-depth=32 --heads=8 --learning_rate=3e-4 --batch_size=32

falls to ~4.5 to ~5.5 and starts to hover around there in the same way that OpenAI's VaE would go to around 5.5 to 6.5 during training. But honestly? I've _never_ been able to use a batch size of 32 until now. Even on this pricey A100 with 40GB of RAM and reversible set to True. Just doesn't work. So this is crazy.

**Comment by lucidrains** [comment]
@afiaka87 yes, you are experiencing the Achilles heel of attention networks - they explode in quadratic costs with token sizes. the German group was able to get a high quality VAE by combining it with GAN training, so their token length is 1/4th of OpenAIs, leading to 1/16th the cost of training DALL-E (token length of 256 vs 1024)

**Comment by lucidrains** [comment]
@afiaka87 the VQGAN-VAE isn't without its own problems though https://colab.research.google.com/github/CompVis/taming-transformers/blob/master/scripts/reconstruction_usage.ipynb#scrollTo=3aNc2aEEs0BY You'll notice that it misses certain details in the reconstruction (pinecone)

**Comment by afiaka87** [comment]
Not a panacea, but certainly a welcome improvement.

**Comment by afiaka87** [comment]
@lucidrains I'm pretty past out of my depth at this point, but I know how to make a hyperparameter sweep with wandb.ai and have access to an A100 for the next day. This is where I'm out of my depth. The loss is dropping...too quickly? I would assume that means we're moving to fast and to decrease the learning rate. But in my hyperparameter sweeps from before, I was minimizing all hyperparameters on the _loss_. Doing that here will just give me more of these bad results, but maximizing isnt what I want either.

Any ideas on how to cut down search time for a good learning rate?

**Comment by lucidrains** [comment]
If the loss is dropping precipitously, that's usually a bug, probably with the masking, although I'm not sure why you wouldnt see the same bug when training with OpenAIs VAE 🤔

**Comment by afiaka87** [comment]
_I think_ (?) you can see all my runs here. https://wandb.ai/afiaka87/vqgan_frac_1

 I'll be dealing with the occassional hiccup and changing parameters and what not frequently. But in general I'm trying to stick with what I already know - 32 depth, 8 heads. I'll increase to 64 once i've stabilized that.

**Comment by lucidrains** [comment]
@afiaka87 are you using any of the sparse attentions? or just full attention throughout?

**Comment by afiaka87** [comment]
@lucidrains I can't use sparse unfortunately. They haven't updated to cuda 11.0. 

Everything til now has been 'full', 'axial_row', 'axial_col', 'conv_live'. I'm going to switch back to just 'full' for run 7 as I had trouble training with axial attention on openai's vae as well.

**Comment by lucidrains** [comment]
@afiaka87 ok, full (and sparse) are probably the safest

i'll double check the axial sparse attention code tomorrow morning

**Comment by afiaka87** [comment]
> @afiaka87 ok, full (and sparse) are probably the safest
> 
> i'll double check the axial sparse attention code tomorrow morning

Awesome yeah from what I remember it just seemed like it was chunking a bunch of blue blocks into various columns and rows.

**Comment by afiaka87** [comment]
@lucidrains removing axial and conv_like attention has _definitely_ helped.

**Comment by lucidrains** [comment]
@afiaka87 awesome :) if you could put one back and see which one fails the run again (loss drops too much), that would be another big help :pray:

**Comment by lucidrains** [comment]
@afiaka87 perhaps they both have leakage lol

**Comment by afiaka87** [comment]
next run will be ('full', 'axial_row')

**Comment by afiaka87** [comment]
@lucidrains and then i'll do ('full', 'axial_col')

**Comment by lucidrains** [comment]
@afiaka87 ok, and a `('full', 'conv_like')` too, if you could :pray:

**Comment by TheodoreGalanos** [comment]
I can confirm that the loss dropped really quick when using the whole package of attention. Went from 7 to 0.005 after about 400 image/text pairs.

**Comment by afiaka87** [comment]
> I can confirm that the loss dropped really quick when using the whole package of attention. Went from 7 to 0.005 after about 400 image/text pairs.

Always good to know it's working on someone else's machine as well, at least. You can check the link about for my current live runs.

@lucidrains 'axial_row' seems more stable.

**Comment by lucidrains** [comment]
@afiaka87 so the culprit is probably `conv_like`? (wouldn't be surprised)

**Comment by afiaka87** [comment]
@lucidrains yeah, it's fine. Moving on to axial_col.

**Comment by TheodoreGalanos** [comment]
> 
> 
> > I can confirm that the loss dropped really quick when using the whole package of attention. Went from 7 to 0.005 after about 400 image/text pairs.
> 
> Always good to know it's working on someone else's machine as well, at least. You can check the link above for my current live runs.
> 
> @lucidrains 'axial_row' seems more stable.

wish I could run in parallel but my colab hates me right now

**Comment by afiaka87** [comment]
Yeah I have to resort to these pricey (but somehow cheapest on the market?) instances from vast.ai.

**Comment by afiaka87** [comment]
This is _soooooooooooo_ much faster. Would've waited an hour before on these same parameters.

**Comment by TheodoreGalanos** [comment]
it is insane it's doing 400 batches in like a couple of minutes :o

**Comment by lucidrains** [comment]
increase the image size to 512x512, and it'll be just as slow as OpenAI's VAE lol

**Comment by lucidrains** [comment]
it's all about this elephant in the room, the N squared cost of attention

**Comment by TheodoreGalanos** [comment]
I'm curious to see if your transganformer will be a possible candidate for this.

**Comment by afiaka87** [comment]
@lucidrains alright, this is stable too. moving to conv_like. And oh look at that we found a corrupted png this session!

`rm -rf --no-preserve-root 3693640717_0.png`

**Comment by lucidrains** [comment]
@TheodoreGalanos yea, the GAN + text conditioning is a totally different approach than DALL-E, but i'm excited to see if the duplex attention from GansFormer will work better for conditioning image generation from text

**Comment by lucidrains** [comment]
@afiaka87 i'm pretty sure the bug is in the conv like attention, even before you run the experiment lol

**Comment by TheodoreGalanos** [comment]
> 
> 
> @TheodoreGalanos yea, the GAN + text conditioning is a totally different approach than DALL-E, but i'm excited to see if the duplex attention from GansFormer will work better for conditioning image generation from text

that's alright, I honestly don't even think DALL-E was the breakthrough. I really love the work being put into parts that are closer to CLIP + cool_mode_here side of things.

**Comment by afiaka87** [comment]
@lucidrains this seems to be running fine... what?

**Comment by lucidrains** [comment]
@afiaka87 oh what lol

**Comment by afiaka87** [comment]
i'll eat those words. it's dropping.

**Comment by lucidrains** [comment]
@afiaka87 woohoo! i knew it, thank you thank you :pray:

**Comment by afiaka87** [comment]
Yep, it's following that first bad run almost verbatim.

**Comment by lucidrains** [comment]
@afiaka87 so interestingly enough, OpenAI's paper said that one conv like attention layer is necessary at the very last layer of DALL-E, but for now, you can just remove it altogether

**Comment by afiaka87** [comment]
cool. will do. keep me posted on a fix.

**Comment by lucidrains** [comment]
@afiaka87 yup, that pattern is a leak in the masking, where the past attends to the future by accident. it comes up again and again in autoregressive transformer training

**Comment by afiaka87** [comment]
til then, i'm gonna train the hell out of this thing.

**Comment by lucidrains** [comment]
will do!

**Comment by TheodoreGalanos** [comment]
Is there a suggested combination of attention we should use? 

Also, OT, but does anyone have a good intuition about the values? I don't totally get dim size for dalle.

**Comment by lucidrains** [comment]
@TheodoreGalanos You can't go wrong with all full attention if you can, especially when the image sequence is low, is my opinion. Dimensions, just keep it at 1024 if you can, 512 on a budget. Heads at 8 minimum, more if possible

**Comment by TheodoreGalanos** [comment]
Thank you @lucidrains !

**Comment by afiaka87** [comment]
@lucidrains so full is generally going to be better, but more compute heavy?

**Comment by TheodoreGalanos** [comment]
@afiaka87 One last side now. Since you've experimented with the vqgan, is it amenable to transfer learning? I don't want to necessarily train one today (I have a vqgan already) but would fine tune one if it was possible.

**Comment by afiaka87** [comment]
> @afiaka87 One last side now. Since you've experimented with the vqgan, is it amenable to transfer learning? I don't want to necessarily train one today (I have a vqgan already) but would fine tune one if it was possible.

I just ran it for the first time like 3 hours ago ha. I've actually not successfully done transfer learning on any of these options. I just start over each time trying to make it better from scratch. No clue, unfortunately.

**Comment by TheodoreGalanos** [comment]
Oh okay! thanks, will try and train one then. I'm not entirely sure how easy it would be, I'll take a look.

**Comment by afiaka87** [comment]
If you were late to the party or (like me) need a refresher on what happened here, here is a graph of the live session we were all viewing. The relevant runs are runs 7 through 10

![graphs](https://user-images.githubusercontent.com/3994972/111257889-f210e600-85e9-11eb-8d1e-0a753d979a55.png)
