### ISSUE TITLE
Implement OpenAI's "Force the top half of an image as input" Feature

### ISSUE THREAD

**Issue by afiaka87** [lucidrains/DALLE-pytorch#90]
This feature is used in the original blog post to show that a sufficiently trained dalle is capable of zero shot visual reasoning about existing imagery. This is _really_ cool to me and I even have some data from that very blog post to test it with!

Please let me know if you need help/compute with this feature. Thanks.

**Comment by lucidrains** [comment]
Yup this is easier than it sounds, will be done this week for sure

**Comment by lucidrains** [comment]
@afiaka87 ok, this is done! here https://github.com/lucidrains/DALLE-pytorch/commit/0eb09e17c29e84aaa4095ee2b852e519cff44576

**Comment by afiaka87** [comment]
Fantastic! Was literally just trying to understand the json they return for those types of prompts actually. 

Let me see if I can't test it out here in about an hour

**Comment by afiaka87** [comment]
@lucidrains I'm having trouble figuring out how exactly to use this. Here's my code:

```python
from torchvision import transforms as T
from PIL import Image
from dalle_pytorch.simple_tokenizer import tokenize, tokenizer, VOCAB_SIZE

# already defined from training.
# dalle = DALLE(vae = vae, **dalle_params).cuda()

image_tranform = T.Compose([
    T.ToTensor()
])

text = "the exact same dog on the top as a sketch on the bottom"
image = Image.open("./the_dog_photo.png")
tokenized_text = tokenize(text).squeeze(0).cuda()
mask = tokenized_text != 0
image_tensor = image_tranform(image)

img_prime = torch.randn(4, 3, 256, 256)

images = dalle.generate_images(
    text,
    mask = mask[:1],
    img = image_tensor,
    # num_init_img_tokens = (14 * 32)
)

images.shape # (4, 3, 256, 256)
> Expected 4-dimensional input for 4-dimensional weight [128, 3, 3, 3], but got 3-dimensional input of size [3, 111, 256] instead
```

This is the image I'm trying to pass in: 

![dog_photo_2](https://user-images.githubusercontent.com/3994972/111556592-f4458280-8758-11eb-925f-2463c3ae12d7.png)

**Comment by lucidrains** [comment]
@afiaka87 added some asserts to the generate_image function https://github.com/lucidrains/DALLE-pytorch/commit/0da8d2852add77dd8e4294f020d7e6a472ac26a3 let me know if you are still seeing the same error!

**Comment by lucidrains** [comment]
@afiaka87 i think the image also needs to have an `unsqueeze(0)`

**Comment by afiaka87** [comment]
> @afiaka87 i think the image also needs to have an `unsqueeze(0)`

@lucidrains Awesome! I'll have a look in the morning.

**Comment by afiaka87** [comment]
"The morning" meant "a week from now" apparently. Looking into this today.

**Comment by afiaka87** [comment]
Following up...
![input](https://user-images.githubusercontent.com/3994972/111556592-f4458280-8758-11eb-925f-2463c3ae12d7.png)
![nother_good_one](https://user-images.githubusercontent.com/3994972/115132334-cf953280-9fc4-11eb-8add-9e359750e86a.jpg)

![close____](https://user-images.githubusercontent.com/3994972/115132323-c60bca80-9fc4-11eb-9b82-99bc4906832c.jpg)

![129](https://user-images.githubusercontent.com/3994972/115132352-08350c00-9fc5-11eb-87bf-d07a4040d4ed.jpg)

**Comment by afiaka87** [comment]
Needs a bit more time perhaps
