### ISSUE TITLE
New Bug in Colab and Some More Wandb Info

### ISSUE THREAD

**Issue by afiaka87** [lucidrains/DALLE-pytorch#96]
There's a bug in the current colab notebook. I've found it's best to put the `import wandb` statement at the top of the cell, despite what their docs tend to say. 

More importantly, I noticed you added the `watch` feature I mentioned. I've unfortunately been having to turn that off lately actually because it chews through disk space in a tmp directory locally, and towards your 100 GiB limit on wandb.ai. I suggest turning it off for the time being.

**Comment by lucidrains** [comment]
@afiaka87 thanks! updated the colab :)
