### ISSUE TITLE
(Bug) Using 'conv_like' attention causes loss to nosedive too quickly

### ISSUE THREAD

**Issue by afiaka87** [lucidrains/DALLE-pytorch#97]
edit: here's all (edit) `four` runs. https://wandb.ai/afiaka87/dalle_coco_train/reports/conv_like-sanity-check--Vmlldzo1MzY3MTg

'conv_like' seems to still have issues at the moment. 

Original post:

> @lucidrains I don't think that was the fix for conv_like. I'm still seeing the behavior from before when I turn it on. 
> 
> https://wandb.ai/afiaka87/dalle_coco_train/reports/dalle-pytorch-attention-issues-using-full-axial_row-axial_col-conv_like---Vmlldzo1MzY2MjY
> 
> That's a report of my current run.  I'm gonna do a re-run with _just_ full_conv again just to make sure it's not due to the combination somehow.
> 
> Edit: okay, just doing a simple 16 depth, 8 heads, 8 batch size run with just 'conv_like' attention. Here's that run:
> https://wandb.ai/afiaka87/dalle_coco_train/runs/36s8nsn9

**Comment by afiaka87** [comment]
okay, just doing a simple 16 depth, 8 heads, 8 batch size run with just 'conv_like' attention. Here's that run:
https://wandb.ai/afiaka87/dalle_coco_train/runs/36s8nsn9

**Comment by afiaka87** [comment]
@lucidrains aaand yep, took a little longer this time but sure enough it's down to that 0.0 to 1.0 region too quickly. 'full_conv' is the culprit. I'm going to double check that i've got the latest branch and run one last time.

**Comment by afiaka87** [comment]
https://wandb.ai/afiaka87/dalle_coco_train/reports/conv_like-sanity-check--Vmlldzo1MzY3MTg

All three runs. Running your latest README update commits on the last one. Anyways, that's as best as I can help from my end. Let me know if you have any ideas.

**Comment by lucidrains** [comment]
- @afiaka87 thanks yet again! this really helps speed up debugging - I think I found another :bug: , by no means could it be the last one though lol https://github.com/lucidrains/DALLE-pytorch/commit/f68cb213a3a687d7b2f0cc6c7f58148bbb89d6c4

**Comment by afiaka87** [comment]
@lucidrains cool ill give it a shot, see if it helped.

**Comment by afiaka87** [comment]
@lucidrains Feel free to check that report again. Seems your latest fix did the trick. Nicely done.

**Comment by lucidrains** [comment]
@afiaka87 awesome :)
